/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package oreplus.init;

import oreplus.block.ZirconOreBlock;
import oreplus.block.ZirconBlockBlock;
import oreplus.block.ZincOreBlock;
import oreplus.block.ZincBlockBlock;
import oreplus.block.YttriumBlockBlock;
import oreplus.block.VoidstoneOreBlock;
import oreplus.block.TungstenOreBlock;
import oreplus.block.TungstenBlockBlock;
import oreplus.block.TopazOreBlock;
import oreplus.block.TopazBlockBlock;
import oreplus.block.TitaniumBlockBlock;
import oreplus.block.TinOreBlock;
import oreplus.block.TinBlockBlock;
import oreplus.block.TanzaniteOreBlock;
import oreplus.block.TanzaniteBlockBlock;
import oreplus.block.SulfurOreBlock;
import oreplus.block.SulfurBlockBlock;
import oreplus.block.SpinelOreBlock;
import oreplus.block.SilverOreBlock;
import oreplus.block.SilverBlockBlock;
import oreplus.block.SapphireOreBlock;
import oreplus.block.SapphireBlockBlock;
import oreplus.block.RubyOreBlock;
import oreplus.block.RubyBlockBlock;
import oreplus.block.RhodochrositeOreBlock;
import oreplus.block.RhodochrositeBlockBlock;
import oreplus.block.PyraliteDebrisBlock;
import oreplus.block.PyraliteBlockBlock;
import oreplus.block.PlatinumOreBlock;
import oreplus.block.PlatinumBlockBlock;
import oreplus.block.PeridotOreBlock;
import oreplus.block.PeridotBlockBlock;
import oreplus.block.PalladiumOreBlock;
import oreplus.block.PalladiumBlockBlock;
import oreplus.block.OpalBlockBlock;
import oreplus.block.ObsidianiteDebrisBlock;
import oreplus.block.ObsidianiteBlockBlock;
import oreplus.block.NickelOreBlock;
import oreplus.block.NickelBlockBlock;
import oreplus.block.NeodymiumOreBlock;
import oreplus.block.NeodymiumBlockBlock;
import oreplus.block.MorganiteOreBlock;
import oreplus.block.MorganiteBlockBlock;
import oreplus.block.MetalScrapBlockBlock;
import oreplus.block.MalachiteOreBlock;
import oreplus.block.MalachiteBlockBlock;
import oreplus.block.MagnetiteOreBlock;
import oreplus.block.MagnetiteBlockBlock;
import oreplus.block.LanthaniumBlockBlock;
import oreplus.block.KyaniteOreBlock;
import oreplus.block.HematiteOreBlock;
import oreplus.block.HematiteBlockBlock;
import oreplus.block.GraphiteOreBlock;
import oreplus.block.GraphiteBlockBlock;
import oreplus.block.GarnetOreBlock;
import oreplus.block.GarnetBlockBlock;
import oreplus.block.GalenaOreBlock;
import oreplus.block.GalenaBlockBlock;
import oreplus.block.GadoliniumOreBlock;
import oreplus.block.GadoliniumBlockBlock;
import oreplus.block.FluoriteOreBlock;
import oreplus.block.FluoriteBlockBlock;
import oreplus.block.DeepslateZirconOreBlock;
import oreplus.block.DeepslateZincOreBlock;
import oreplus.block.DeepslateVoidstoneOreBlock;
import oreplus.block.DeepslateTungstenOreBlock;
import oreplus.block.DeepslateTopazOreBlock;
import oreplus.block.DeepslateTinOreBlock;
import oreplus.block.DeepslateTanzaniteOreBlock;
import oreplus.block.DeepslateSpinelOreBlock;
import oreplus.block.DeepslateSilverOreBlock;
import oreplus.block.DeepslateSapphireOreBlock;
import oreplus.block.DeepslateRubyOreBlock;
import oreplus.block.DeepslateRhodochrositeOreBlock;
import oreplus.block.DeepslatePlatinumOreBlock;
import oreplus.block.DeepslatePeridotOreBlock;
import oreplus.block.DeepslatePalladiumOreBlock;
import oreplus.block.DeepslateOsmiumOreBlock;
import oreplus.block.DeepslateNiobiumOreBlock;
import oreplus.block.DeepslateNickelOreBlock;
import oreplus.block.DeepslateNeodymiumOreBlock;
import oreplus.block.DeepslateMorganiteOreBlock;
import oreplus.block.DeepslateMolybdenumOreBlock;
import oreplus.block.DeepslateMalachiteOreBlock;
import oreplus.block.DeepslateMagnetiteOreBlock;
import oreplus.block.DeepslateKyaniteOreBlock;
import oreplus.block.DeepslateHematiteOreBlock;
import oreplus.block.DeepslateGraphiteOreBlock;
import oreplus.block.DeepslateGarnetOreBlock;
import oreplus.block.DeepslateGalenaOreBlock;
import oreplus.block.DeepslateGadoliniumOreBlock;
import oreplus.block.DeepslateFluoriteOreBlock;
import oreplus.block.DeepslateCobaltOreBlock;
import oreplus.block.DeepslateCinnabarBlock;
import oreplus.block.DeepslateCeriumOreBlock;
import oreplus.block.DeepslateBoraxOreBlock;
import oreplus.block.DeepslateBismuthOreBlock;
import oreplus.block.DeepslateBauxiteOreBlock;
import oreplus.block.DeepslateAzuriteOreBlock;
import oreplus.block.DeepslateAquamarineOreBlock;
import oreplus.block.DeepslateAlexandriteOreBlock;
import oreplus.block.CobaltOreBlock;
import oreplus.block.CobaltBlockBlock;
import oreplus.block.CinnabarOreBlock;
import oreplus.block.CinnabarBlockBlock;
import oreplus.block.ChromiumBlockBlock;
import oreplus.block.CeriumOreBlock;
import oreplus.block.CeriumBlockBlock;
import oreplus.block.CelestiumOreBlock;
import oreplus.block.CarbonBlockBlock;
import oreplus.block.BoraxOreBlock;
import oreplus.block.BoraxBlockBlock;
import oreplus.block.BismuthOreBlock;
import oreplus.block.BauxiteOreBlock;
import oreplus.block.BauxiteBlockBlock;
import oreplus.block.AzuriteOreBlock;
import oreplus.block.AzuriteBlockBlock;
import oreplus.block.AquamarineOreBlock;
import oreplus.block.AquamarineBlockBlock;
import oreplus.block.AlloyFurnaceBlock;
import oreplus.block.AlexandriteOreBlock;
import oreplus.block.AlexandriteBlockBlock;
import oreplus.block.AetheriumBlockBlock;
import oreplus.block.AethelgardDebrisBlock;
import oreplus.block.AethelgardBlockBlock;
import oreplus.block.AdamantiteOreBlock;

import oreplus.OrePlusMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

public class OrePlusModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, OrePlusMod.MODID);
	public static final RegistryObject<Block> SILVER_ORE = REGISTRY.register("silver_ore", () -> new SilverOreBlock());
	public static final RegistryObject<Block> SILVER_BLOCK = REGISTRY.register("silver_block", () -> new SilverBlockBlock());
	public static final RegistryObject<Block> PLATINUM_ORE = REGISTRY.register("platinum_ore", () -> new PlatinumOreBlock());
	public static final RegistryObject<Block> PLATINUM_BLOCK = REGISTRY.register("platinum_block", () -> new PlatinumBlockBlock());
	public static final RegistryObject<Block> TITANIUM_BLOCK = REGISTRY.register("titanium_block", () -> new TitaniumBlockBlock());
	public static final RegistryObject<Block> TUNGSTEN_ORE = REGISTRY.register("tungsten_ore", () -> new TungstenOreBlock());
	public static final RegistryObject<Block> TUNGSTEN_BLOCK = REGISTRY.register("tungsten_block", () -> new TungstenBlockBlock());
	public static final RegistryObject<Block> COBALT_ORE = REGISTRY.register("cobalt_ore", () -> new CobaltOreBlock());
	public static final RegistryObject<Block> COBALT_BLOCK = REGISTRY.register("cobalt_block", () -> new CobaltBlockBlock());
	public static final RegistryObject<Block> NICKEL_ORE = REGISTRY.register("nickel_ore", () -> new NickelOreBlock());
	public static final RegistryObject<Block> NICKEL_BLOCK = REGISTRY.register("nickel_block", () -> new NickelBlockBlock());
	public static final RegistryObject<Block> CHROMIUM_BLOCK = REGISTRY.register("chromium_block", () -> new ChromiumBlockBlock());
	public static final RegistryObject<Block> PALLADIUM_ORE = REGISTRY.register("palladium_ore", () -> new PalladiumOreBlock());
	public static final RegistryObject<Block> PALLADIUM_BLOCK = REGISTRY.register("palladium_block", () -> new PalladiumBlockBlock());
	public static final RegistryObject<Block> RUBY_ORE = REGISTRY.register("ruby_ore", () -> new RubyOreBlock());
	public static final RegistryObject<Block> RUBY_BLOCK = REGISTRY.register("ruby_block", () -> new RubyBlockBlock());
	public static final RegistryObject<Block> SAPPHIRE_ORE = REGISTRY.register("sapphire_ore", () -> new SapphireOreBlock());
	public static final RegistryObject<Block> SAPPHIRE_BLOCK = REGISTRY.register("sapphire_block", () -> new SapphireBlockBlock());
	public static final RegistryObject<Block> TOPAZ_ORE = REGISTRY.register("topaz_ore", () -> new TopazOreBlock());
	public static final RegistryObject<Block> TOPAZ_BLOCK = REGISTRY.register("topaz_block", () -> new TopazBlockBlock());
	public static final RegistryObject<Block> AQUAMARINE_ORE = REGISTRY.register("aquamarine_ore", () -> new AquamarineOreBlock());
	public static final RegistryObject<Block> AQUAMARINE_BLOCK = REGISTRY.register("aquamarine_block", () -> new AquamarineBlockBlock());
	public static final RegistryObject<Block> GARNET_ORE = REGISTRY.register("garnet_ore", () -> new GarnetOreBlock());
	public static final RegistryObject<Block> GARNET_BLOCK = REGISTRY.register("garnet_block", () -> new GarnetBlockBlock());
	public static final RegistryObject<Block> OPAL_BLOCK = REGISTRY.register("opal_block", () -> new OpalBlockBlock());
	public static final RegistryObject<Block> TANZANITE_ORE = REGISTRY.register("tanzanite_ore", () -> new TanzaniteOreBlock());
	public static final RegistryObject<Block> TANZANITE_BLOCK = REGISTRY.register("tanzanite_block", () -> new TanzaniteBlockBlock());
	public static final RegistryObject<Block> MORGANITE_ORE = REGISTRY.register("morganite_ore", () -> new MorganiteOreBlock());
	public static final RegistryObject<Block> MORGANITE_BLOCK = REGISTRY.register("morganite_block", () -> new MorganiteBlockBlock());
	public static final RegistryObject<Block> SULFUR_ORE = REGISTRY.register("sulfur_ore", () -> new SulfurOreBlock());
	public static final RegistryObject<Block> GRAPHITE_ORE = REGISTRY.register("graphite_ore", () -> new GraphiteOreBlock());
	public static final RegistryObject<Block> BAUXITE_ORE = REGISTRY.register("bauxite_ore", () -> new BauxiteOreBlock());
	public static final RegistryObject<Block> CINNABAR_ORE = REGISTRY.register("cinnabar_ore", () -> new CinnabarOreBlock());
	public static final RegistryObject<Block> BORAX_ORE = REGISTRY.register("borax_ore", () -> new BoraxOreBlock());
	public static final RegistryObject<Block> GALENA_ORE = REGISTRY.register("galena_ore", () -> new GalenaOreBlock());
	public static final RegistryObject<Block> MAGNETITE_ORE = REGISTRY.register("magnetite_ore", () -> new MagnetiteOreBlock());
	public static final RegistryObject<Block> HEMATITE_ORE = REGISTRY.register("hematite_ore", () -> new HematiteOreBlock());
	public static final RegistryObject<Block> MALACHITE_ORE = REGISTRY.register("malachite_ore", () -> new MalachiteOreBlock());
	public static final RegistryObject<Block> AZURITE_ORE = REGISTRY.register("azurite_ore", () -> new AzuriteOreBlock());
	public static final RegistryObject<Block> NEODYMIUM_ORE = REGISTRY.register("neodymium_ore", () -> new NeodymiumOreBlock());
	public static final RegistryObject<Block> NEODYMIUM_BLOCK = REGISTRY.register("neodymium_block", () -> new NeodymiumBlockBlock());
	public static final RegistryObject<Block> LANTHANIUM_BLOCK = REGISTRY.register("lanthanium_block", () -> new LanthaniumBlockBlock());
	public static final RegistryObject<Block> CERIUM_ORE = REGISTRY.register("cerium_ore", () -> new CeriumOreBlock());
	public static final RegistryObject<Block> YTTRIUM_BLOCK = REGISTRY.register("yttrium_block", () -> new YttriumBlockBlock());
	public static final RegistryObject<Block> GADOLINIUM_ORE = REGISTRY.register("gadolinium_ore", () -> new GadoliniumOreBlock());
	public static final RegistryObject<Block> GADOLINIUM_BLOCK = REGISTRY.register("gadolinium_block", () -> new GadoliniumBlockBlock());
	public static final RegistryObject<Block> ALEXANDRITE_ORE = REGISTRY.register("alexandrite_ore", () -> new AlexandriteOreBlock());
	public static final RegistryObject<Block> ALEXANDRITE_BLOCK = REGISTRY.register("alexandrite_block", () -> new AlexandriteBlockBlock());
	public static final RegistryObject<Block> PERIDOT_ORE = REGISTRY.register("peridot_ore", () -> new PeridotOreBlock());
	public static final RegistryObject<Block> PERIDOT_BLOCK = REGISTRY.register("peridot_block", () -> new PeridotBlockBlock());
	public static final RegistryObject<Block> ZIRCON_ORE = REGISTRY.register("zircon_ore", () -> new ZirconOreBlock());
	public static final RegistryObject<Block> ZIRCON_BLOCK = REGISTRY.register("zircon_block", () -> new ZirconBlockBlock());
	public static final RegistryObject<Block> RHODOCHROSITE_ORE = REGISTRY.register("rhodochrosite_ore", () -> new RhodochrositeOreBlock());
	public static final RegistryObject<Block> RHODOCHROSITE_BLOCK = REGISTRY.register("rhodochrosite_block", () -> new RhodochrositeBlockBlock());
	public static final RegistryObject<Block> FLUORITE_ORE = REGISTRY.register("fluorite_ore", () -> new FluoriteOreBlock());
	public static final RegistryObject<Block> FLUORITE_BLOCK = REGISTRY.register("fluorite_block", () -> new FluoriteBlockBlock());
	public static final RegistryObject<Block> ALLOY_FURNACE = REGISTRY.register("alloy_furnace", () -> new AlloyFurnaceBlock());
	public static final RegistryObject<Block> ADAMANTITE_ORE = REGISTRY.register("adamantite_ore", () -> new AdamantiteOreBlock());
	public static final RegistryObject<Block> CELESTIUM_ORE = REGISTRY.register("celestium_ore", () -> new CelestiumOreBlock());
	public static final RegistryObject<Block> VOIDSTONE_ORE = REGISTRY.register("voidstone_ore", () -> new VoidstoneOreBlock());
	public static final RegistryObject<Block> CARBON_BLOCK = REGISTRY.register("carbon_block", () -> new CarbonBlockBlock());
	public static final RegistryObject<Block> DEEPSLATE_TUNGSTEN_ORE = REGISTRY.register("deepslate_tungsten_ore", () -> new DeepslateTungstenOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_PALLADIUM_ORE = REGISTRY.register("deepslate_palladium_ore", () -> new DeepslatePalladiumOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_GRAPHITE_ORE = REGISTRY.register("deepslate_graphite_ore", () -> new DeepslateGraphiteOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_CINNABAR_ORE = REGISTRY.register("deepslate_cinnabar_ore", () -> new DeepslateCinnabarBlock());
	public static final RegistryObject<Block> DEEPSLATE_BORAX_ORE = REGISTRY.register("deepslate_borax_ore", () -> new DeepslateBoraxOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_GALENA_ORE = REGISTRY.register("deepslate_galena_ore", () -> new DeepslateGalenaOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_MAGNETITE_ORE = REGISTRY.register("deepslate_magnetite_ore", () -> new DeepslateMagnetiteOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_MALACHITE_ORE = REGISTRY.register("deepslate_malachite_ore", () -> new DeepslateMalachiteOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_AZURITE_ORE = REGISTRY.register("deepslate_azurite_ore", () -> new DeepslateAzuriteOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_NEODYMIUM_ORE = REGISTRY.register("deepslate_neodymium_ore", () -> new DeepslateNeodymiumOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_CERIUM_ORE = REGISTRY.register("deepslate_cerium_ore", () -> new DeepslateCeriumOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_GADOLINIUM_ORE = REGISTRY.register("deepslate_gadolinium_ore", () -> new DeepslateGadoliniumOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_SILVER_ORE = REGISTRY.register("deepslate_silver_ore", () -> new DeepslateSilverOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_PLATINUM_ORE = REGISTRY.register("deepslate_platinum_ore", () -> new DeepslatePlatinumOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_COBALT_ORE = REGISTRY.register("deepslate_cobalt_ore", () -> new DeepslateCobaltOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_NICKEL_ORE = REGISTRY.register("deepslate_nickel_ore", () -> new DeepslateNickelOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_BAUXITE_ORE = REGISTRY.register("deepslate_bauxite_ore", () -> new DeepslateBauxiteOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_RUBY_ORE = REGISTRY.register("deepslate_ruby_ore", () -> new DeepslateRubyOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_SAPPHIRE_ORE = REGISTRY.register("deepslate_sapphire_ore", () -> new DeepslateSapphireOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_TOPAZ_ORE = REGISTRY.register("deepslate_topaz_ore", () -> new DeepslateTopazOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_AQUAMARINE_ORE = REGISTRY.register("deepslate_aquamarine_ore", () -> new DeepslateAquamarineOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_GARNET_ORE = REGISTRY.register("deepslate_garnet_ore", () -> new DeepslateGarnetOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_TANZANITE_ORE = REGISTRY.register("deepslate_tanzanite_ore", () -> new DeepslateTanzaniteOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_MORGANITE_ORE = REGISTRY.register("deepslate_morganite_ore", () -> new DeepslateMorganiteOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_ALEXANDRITE_ORE = REGISTRY.register("deepslate_alexandrite_ore", () -> new DeepslateAlexandriteOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_PERIDOT_ORE = REGISTRY.register("deepslate_peridot_ore", () -> new DeepslatePeridotOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_ZIRCON_ORE = REGISTRY.register("deepslate_zircon_ore", () -> new DeepslateZirconOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_RHODOCHROSITE_ORE = REGISTRY.register("deepslate_rhodochrosite_ore", () -> new DeepslateRhodochrositeOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_FLUORITE_ORE = REGISTRY.register("deepslate_fluorite_ore", () -> new DeepslateFluoriteOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_VOIDSTONE_ORE = REGISTRY.register("deepslate_voidstone_ore", () -> new DeepslateVoidstoneOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_HEMATITE_ORE = REGISTRY.register("deepslate_hematite_ore", () -> new DeepslateHematiteOreBlock());
	public static final RegistryObject<Block> TIN_ORE = REGISTRY.register("tin_ore", () -> new TinOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_TIN_ORE = REGISTRY.register("deepslate_tin_ore", () -> new DeepslateTinOreBlock());
	public static final RegistryObject<Block> TIN_BLOCK = REGISTRY.register("tin_block", () -> new TinBlockBlock());
	public static final RegistryObject<Block> ZINC_ORE = REGISTRY.register("zinc_ore", () -> new ZincOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_ZINC_ORE = REGISTRY.register("deepslate_zinc_ore", () -> new DeepslateZincOreBlock());
	public static final RegistryObject<Block> ZINC_BLOCK = REGISTRY.register("zinc_block", () -> new ZincBlockBlock());
	public static final RegistryObject<Block> METAL_SCRAP_BLOCK = REGISTRY.register("metal_scrap_block", () -> new MetalScrapBlockBlock());
	public static final RegistryObject<Block> AETHERIUM_BLOCK = REGISTRY.register("aetherium_block", () -> new AetheriumBlockBlock());
	public static final RegistryObject<Block> AETHELGARD_DEBRIS = REGISTRY.register("aethelgard_debris", () -> new AethelgardDebrisBlock());
	public static final RegistryObject<Block> AETHELGARD_BLOCK = REGISTRY.register("aethelgard_block", () -> new AethelgardBlockBlock());
	public static final RegistryObject<Block> OBSIDIANITE_DEBRIS = REGISTRY.register("obsidianite_debris", () -> new ObsidianiteDebrisBlock());
	public static final RegistryObject<Block> OBSIDIANITE_BLOCK = REGISTRY.register("obsidianite_block", () -> new ObsidianiteBlockBlock());
	public static final RegistryObject<Block> PYRALITE_DEBRIS = REGISTRY.register("pyralite_debris", () -> new PyraliteDebrisBlock());
	public static final RegistryObject<Block> PYRALITE_BLOCK = REGISTRY.register("pyralite_block", () -> new PyraliteBlockBlock());
	public static final RegistryObject<Block> SULFUR_BLOCK = REGISTRY.register("sulfur_block", () -> new SulfurBlockBlock());
	public static final RegistryObject<Block> GRAPHITE_BLOCK = REGISTRY.register("graphite_block", () -> new GraphiteBlockBlock());
	public static final RegistryObject<Block> BAUXITE_BLOCK = REGISTRY.register("bauxite_block", () -> new BauxiteBlockBlock());
	public static final RegistryObject<Block> CINNABAR_BLOCK = REGISTRY.register("cinnabar_block", () -> new CinnabarBlockBlock());
	public static final RegistryObject<Block> BORAX_BLOCK = REGISTRY.register("borax_block", () -> new BoraxBlockBlock());
	public static final RegistryObject<Block> GALENA_BLOCK = REGISTRY.register("galena_block", () -> new GalenaBlockBlock());
	public static final RegistryObject<Block> MAGNETITE_BLOCK = REGISTRY.register("magnetite_block", () -> new MagnetiteBlockBlock());
	public static final RegistryObject<Block> HEMATITE_BLOCK = REGISTRY.register("hematite_block", () -> new HematiteBlockBlock());
	public static final RegistryObject<Block> MALACHITE_BLOCK = REGISTRY.register("malachite_block", () -> new MalachiteBlockBlock());
	public static final RegistryObject<Block> AZURITE_BLOCK = REGISTRY.register("azurite_block", () -> new AzuriteBlockBlock());
	public static final RegistryObject<Block> CERIUM_BLOCK = REGISTRY.register("cerium_block", () -> new CeriumBlockBlock());
	public static final RegistryObject<Block> DEEPSLATE_MOLYBDENUM_ORE = REGISTRY.register("deepslate_molybdenum_ore", () -> new DeepslateMolybdenumOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_NIOBIUM_ORE = REGISTRY.register("deepslate_niobium_ore", () -> new DeepslateNiobiumOreBlock());
	public static final RegistryObject<Block> BISMUTH_ORE = REGISTRY.register("bismuth_ore", () -> new BismuthOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_BISMUTH_ORE = REGISTRY.register("deepslate_bismuth_ore", () -> new DeepslateBismuthOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_OSMIUM_ORE = REGISTRY.register("deepslate_osmium_ore", () -> new DeepslateOsmiumOreBlock());
	public static final RegistryObject<Block> SPINEL_ORE = REGISTRY.register("spinel_ore", () -> new SpinelOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_SPINEL_ORE = REGISTRY.register("deepslate_spinel_ore", () -> new DeepslateSpinelOreBlock());
	public static final RegistryObject<Block> KYANITE_ORE = REGISTRY.register("kyanite_ore", () -> new KyaniteOreBlock());
	public static final RegistryObject<Block> DEEPSLATE_KYANITE_ORE = REGISTRY.register("deepslate_kyanite_ore", () -> new DeepslateKyaniteOreBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}