/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package oreplus.init;

import oreplus.item.ZircongemSwordItem;
import oreplus.item.ZircongemShovelItem;
import oreplus.item.ZircongemPickaxeItem;
import oreplus.item.ZircongemHoeItem;
import oreplus.item.ZircongemAxeItem;
import oreplus.item.ZircongemArmorItem;
import oreplus.item.ZirconItem;
import oreplus.item.ZincItem;
import oreplus.item.ZincDustItem;
import oreplus.item.YttriumSwordItem;
import oreplus.item.YttriumShovelItem;
import oreplus.item.YttriumPickaxeItem;
import oreplus.item.YttriumIngotItem;
import oreplus.item.YttriumHoeItem;
import oreplus.item.YttriumAxeItem;
import oreplus.item.YttriumArmorItem;
import oreplus.item.VoidstoneItem;
import oreplus.item.VoidToolItem;
import oreplus.item.VoidLeakItem;
import oreplus.item.TungstenSwordItem;
import oreplus.item.TungstenShovelItem;
import oreplus.item.TungstenPickaxeItem;
import oreplus.item.TungstenIngotItem;
import oreplus.item.TungstenHoeItem;
import oreplus.item.TungstenAxeItem;
import oreplus.item.TungstenArmorItem;
import oreplus.item.TopazgemSwordItem;
import oreplus.item.TopazgemShovelItem;
import oreplus.item.TopazgemPickaxeItem;
import oreplus.item.TopazgemHoeItem;
import oreplus.item.TopazgemAxeItem;
import oreplus.item.TopazItem;
import oreplus.item.TitaniumSwordItem;
import oreplus.item.TitaniumShovelItem;
import oreplus.item.TitaniumPickaxeItem;
import oreplus.item.TitaniumIngotItem;
import oreplus.item.TitaniumHoeItem;
import oreplus.item.TitaniumAxeItem;
import oreplus.item.TitaniumArmorItem;
import oreplus.item.TinItem;
import oreplus.item.TinDustItem;
import oreplus.item.TanzanitegemArmorItem;
import oreplus.item.TanzaniteItem;
import oreplus.item.SulfurItem;
import oreplus.item.SulfurDustItem;
import oreplus.item.SteelSwordItem;
import oreplus.item.SteelShovelItem;
import oreplus.item.SteelPickaxeItem;
import oreplus.item.SteelItem;
import oreplus.item.SteelHoeItem;
import oreplus.item.SteelAxeItem;
import oreplus.item.SteelArmorItem;
import oreplus.item.SilverSwordItem;
import oreplus.item.SilverShovelItem;
import oreplus.item.SilverPickaxeItem;
import oreplus.item.SilverIngotItem;
import oreplus.item.SilverHoeItem;
import oreplus.item.SilverAxeItem;
import oreplus.item.SilverArmorItem;
import oreplus.item.SapphiregemSwordItem;
import oreplus.item.SapphiregemShovelItem;
import oreplus.item.SapphiregemPickaxeItem;
import oreplus.item.SapphiregemHoeItem;
import oreplus.item.SapphiregemAxeItem;
import oreplus.item.SapphireItem;
import oreplus.item.RubygemSwordItem;
import oreplus.item.RubygemShovelItem;
import oreplus.item.RubygemPickaxeItem;
import oreplus.item.RubygemHoeItem;
import oreplus.item.RubygemAxeItem;
import oreplus.item.RubygemArmorItem;
import oreplus.item.RubyItem;
import oreplus.item.RoseSwordItem;
import oreplus.item.RoseShovelItem;
import oreplus.item.RosePickaxeItem;
import oreplus.item.RoseHoeItem;
import oreplus.item.RoseGoldItem;
import oreplus.item.RoseGoldIngotArmorItem;
import oreplus.item.RoseAxeItem;
import oreplus.item.RhodochrositeItem;
import oreplus.item.RhodochrositeArmorItem;
import oreplus.item.RawTungstenItem;
import oreplus.item.RawSilverItem;
import oreplus.item.RawPlatinumItem;
import oreplus.item.RawPalladiumItem;
import oreplus.item.RawNickelItem;
import oreplus.item.RawNeodymiumItem;
import oreplus.item.RawCobaltItem;
import oreplus.item.PyraliteSwordItem;
import oreplus.item.PyraliteShovelItem;
import oreplus.item.PyraliteShardItem;
import oreplus.item.PyralitePickaxeItem;
import oreplus.item.PyraliteIngotItem;
import oreplus.item.PyraliteHoeItem;
import oreplus.item.PyraliteAxeItem;
import oreplus.item.PlatinumSwordItem;
import oreplus.item.PlatinumShovelItem;
import oreplus.item.PlatinumPickaxeItem;
import oreplus.item.PlatinumIngotItem;
import oreplus.item.PlatinumHoeItem;
import oreplus.item.PlatinumAxeItem;
import oreplus.item.PlatinumArmorItem;
import oreplus.item.PeridotSwordItem;
import oreplus.item.PeridotShovelItem;
import oreplus.item.PeridotPickaxeItem;
import oreplus.item.PeridotItem;
import oreplus.item.PeridotHoeItem;
import oreplus.item.PeridotAxeItem;
import oreplus.item.PeridotArmorItem;
import oreplus.item.PalladiumSwordItem;
import oreplus.item.PalladiumShovelItem;
import oreplus.item.PalladiumPickaxeItem;
import oreplus.item.PalladiumItem;
import oreplus.item.PalladiumIngotItem;
import oreplus.item.PalladiumHoeItem;
import oreplus.item.PalladiumAxeItem;
import oreplus.item.OrichalcumSwordItem;
import oreplus.item.OrichalcumShovelItem;
import oreplus.item.OrichalcumPickaxeItem;
import oreplus.item.OrichalcumItem;
import oreplus.item.OrichalcumHoeItem;
import oreplus.item.OrichalcumAxeItem;
import oreplus.item.OrichalcumArmorItem;
import oreplus.item.OpalSwordItem;
import oreplus.item.OpalShovelItem;
import oreplus.item.OpalPickaxeItem;
import oreplus.item.OpalItem;
import oreplus.item.OpalHoeItem;
import oreplus.item.OpalGemArmorItem;
import oreplus.item.OpalAxeItem;
import oreplus.item.ObsidianiteSwordItem;
import oreplus.item.ObsidianiteShovelItem;
import oreplus.item.ObsidianiteShardItem;
import oreplus.item.ObsidianitePickaxeItem;
import oreplus.item.ObsidianiteIngotItem;
import oreplus.item.ObsidianiteHoeItem;
import oreplus.item.ObsidianiteAxeItem;
import oreplus.item.NickelSwordItem;
import oreplus.item.NickelShovelItem;
import oreplus.item.NickelPickaxeItem;
import oreplus.item.NickelIngotItem;
import oreplus.item.NickelHoeItem;
import oreplus.item.NickelAxeItem;
import oreplus.item.NickelArmorItem;
import oreplus.item.NeodymiumSwordItem;
import oreplus.item.NeodymiumShovelItem;
import oreplus.item.NeodymiumPickaxeItem;
import oreplus.item.NeodymiumIngotItem;
import oreplus.item.NeodymiumHoeItem;
import oreplus.item.NeodymiumAxeItem;
import oreplus.item.NeodymiumArmorItem;
import oreplus.item.MorganiteItem;
import oreplus.item.MorganiteArmorItem;
import oreplus.item.MithrilSwordItem;
import oreplus.item.MithrilShovelItem;
import oreplus.item.MithrilPickaxeItem;
import oreplus.item.MithrilItem;
import oreplus.item.MithrilHoeItem;
import oreplus.item.MithrilAxeItem;
import oreplus.item.MithrilArmorItem;
import oreplus.item.MetalScrapItem;
import oreplus.item.MalachiteItem;
import oreplus.item.MalachiteDustItem;
import oreplus.item.MagnetiteItem;
import oreplus.item.MagnetiteDustItem;
import oreplus.item.LanthaniumSwordItem;
import oreplus.item.LanthaniumShovelItem;
import oreplus.item.LanthaniumPickaxeItem;
import oreplus.item.LanthaniumItem;
import oreplus.item.LanthaniumIngotItem;
import oreplus.item.LanthaniumHoeItem;
import oreplus.item.LanthaniumAxeItem;
import oreplus.item.HematiteItem;
import oreplus.item.HematiteDustItem;
import oreplus.item.GraphiteItem;
import oreplus.item.GraphiteDustItem;
import oreplus.item.GarnetgemSwordItem;
import oreplus.item.GarnetgemShovelItem;
import oreplus.item.GarnetgemPickaxeItem;
import oreplus.item.GarnetgemHoeItem;
import oreplus.item.GarnetgemAxeItem;
import oreplus.item.GarnetgemArmorItem;
import oreplus.item.GarnetItem;
import oreplus.item.GalenaItem;
import oreplus.item.GalenaDustItem;
import oreplus.item.GadoliniumingotItem;
import oreplus.item.GadoliniumSwordItem;
import oreplus.item.GadoliniumShovelItem;
import oreplus.item.GadoliniumPickaxeItem;
import oreplus.item.GadoliniumHoeItem;
import oreplus.item.GadoliniumDustItem;
import oreplus.item.GadoliniumAxeItem;
import oreplus.item.GadoliniumArmorItem;
import oreplus.item.FluoriteItem;
import oreplus.item.FluoriteArmorItem;
import oreplus.item.Electrum_IngotArmorItem;
import oreplus.item.ElectrumSwordItem;
import oreplus.item.ElectrumShovelItem;
import oreplus.item.ElectrumPickaxeItem;
import oreplus.item.ElectrumItem;
import oreplus.item.ElectrumHoeItem;
import oreplus.item.ElectrumAxeItem;
import oreplus.item.CobaltSwordItem;
import oreplus.item.CobaltShovelItem;
import oreplus.item.CobaltPickaxeItem;
import oreplus.item.CobaltIngotItem;
import oreplus.item.CobaltHoeItem;
import oreplus.item.CobaltAxeItem;
import oreplus.item.CobaltArmorItem;
import oreplus.item.CinnabarItem;
import oreplus.item.CinnabarDustItem;
import oreplus.item.ChromiumSwordItem;
import oreplus.item.ChromiumShovelItem;
import oreplus.item.ChromiumPickaxeItem;
import oreplus.item.ChromiumIngotItem;
import oreplus.item.ChromiumHoeItem;
import oreplus.item.ChromiumAxeItem;
import oreplus.item.ChromiumArmorItem;
import oreplus.item.CeriumItem;
import oreplus.item.CeriumDustItem;
import oreplus.item.CelestiumPickaxeItem;
import oreplus.item.CelestiumItem;
import oreplus.item.CarbonItem;
import oreplus.item.BronzeSwordItem;
import oreplus.item.BronzeShovelItem;
import oreplus.item.BronzePickaxeItem;
import oreplus.item.BronzeItem;
import oreplus.item.BronzeHoeItem;
import oreplus.item.BronzeAxeItem;
import oreplus.item.BronzeArmorItem;
import oreplus.item.BrassSwordItem;
import oreplus.item.BrassShovelItem;
import oreplus.item.BrassPickaxeItem;
import oreplus.item.BrassItem;
import oreplus.item.BrassHoeItem;
import oreplus.item.BrassAxeItem;
import oreplus.item.BrassArmorItem;
import oreplus.item.BoraxItem;
import oreplus.item.BoraxDustItem;
import oreplus.item.BauxiteItem;
import oreplus.item.BauxiteDustItem;
import oreplus.item.AzuriteItem;
import oreplus.item.AzuriteDustItem;
import oreplus.item.AquamarineItem;
import oreplus.item.AquamarineArmorArmorItem;
import oreplus.item.AlexandritegemArmorItem;
import oreplus.item.AlexandriteItem;
import oreplus.item.AetheriumToolItem;
import oreplus.item.AetheriumStarItem;
import oreplus.item.AetheriumItem;
import oreplus.item.AethelgardSwordItem;
import oreplus.item.AethelgardShovelItem;
import oreplus.item.AethelgardShardItem;
import oreplus.item.AethelgardPickaxeItem;
import oreplus.item.AethelgardIngotItem;
import oreplus.item.AethelgardHoeItem;
import oreplus.item.AethelgardAxeItem;
import oreplus.item.AdamantiteSwordItem;
import oreplus.item.AdamantiteShovelItem;
import oreplus.item.AdamantitePickaxeItem;
import oreplus.item.AdamantiteItem;
import oreplus.item.AdamantiteHoeItem;
import oreplus.item.AdamantiteDustItem;
import oreplus.item.AdamantiteAxeItem;

import oreplus.OrePlusMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class OrePlusModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, OrePlusMod.MODID);
	public static final RegistryObject<Item> SILVER_INGOT = REGISTRY.register("silver_ingot", () -> new SilverIngotItem());
	public static final RegistryObject<Item> SILVER_ORE = block(OrePlusModBlocks.SILVER_ORE);
	public static final RegistryObject<Item> SILVER_BLOCK = block(OrePlusModBlocks.SILVER_BLOCK);
	public static final RegistryObject<Item> PLATINUM_INGOT = REGISTRY.register("platinum_ingot", () -> new PlatinumIngotItem());
	public static final RegistryObject<Item> PLATINUM_ORE = block(OrePlusModBlocks.PLATINUM_ORE);
	public static final RegistryObject<Item> PLATINUM_BLOCK = block(OrePlusModBlocks.PLATINUM_BLOCK);
	public static final RegistryObject<Item> TITANIUM_INGOT = REGISTRY.register("titanium_ingot", () -> new TitaniumIngotItem());
	public static final RegistryObject<Item> TITANIUM_BLOCK = block(OrePlusModBlocks.TITANIUM_BLOCK);
	public static final RegistryObject<Item> TUNGSTEN_INGOT = REGISTRY.register("tungsten_ingot", () -> new TungstenIngotItem());
	public static final RegistryObject<Item> TUNGSTEN_ORE = block(OrePlusModBlocks.TUNGSTEN_ORE);
	public static final RegistryObject<Item> TUNGSTEN_BLOCK = block(OrePlusModBlocks.TUNGSTEN_BLOCK);
	public static final RegistryObject<Item> COBALT_INGOT = REGISTRY.register("cobalt_ingot", () -> new CobaltIngotItem());
	public static final RegistryObject<Item> COBALT_ORE = block(OrePlusModBlocks.COBALT_ORE);
	public static final RegistryObject<Item> COBALT_BLOCK = block(OrePlusModBlocks.COBALT_BLOCK);
	public static final RegistryObject<Item> NICKEL_INGOT = REGISTRY.register("nickel_ingot", () -> new NickelIngotItem());
	public static final RegistryObject<Item> NICKEL_ORE = block(OrePlusModBlocks.NICKEL_ORE);
	public static final RegistryObject<Item> NICKEL_BLOCK = block(OrePlusModBlocks.NICKEL_BLOCK);
	public static final RegistryObject<Item> CHROMIUM_INGOT = REGISTRY.register("chromium_ingot", () -> new ChromiumIngotItem());
	public static final RegistryObject<Item> CHROMIUM_BLOCK = block(OrePlusModBlocks.CHROMIUM_BLOCK);
	public static final RegistryObject<Item> PALLADIUM_INGOT = REGISTRY.register("palladium_ingot", () -> new PalladiumIngotItem());
	public static final RegistryObject<Item> PALLADIUM_ORE = block(OrePlusModBlocks.PALLADIUM_ORE);
	public static final RegistryObject<Item> PALLADIUM_BLOCK = block(OrePlusModBlocks.PALLADIUM_BLOCK);
	public static final RegistryObject<Item> RUBY = REGISTRY.register("ruby", () -> new RubyItem());
	public static final RegistryObject<Item> RUBY_ORE = block(OrePlusModBlocks.RUBY_ORE);
	public static final RegistryObject<Item> RUBY_BLOCK = block(OrePlusModBlocks.RUBY_BLOCK);
	public static final RegistryObject<Item> SAPPHIRE = REGISTRY.register("sapphire", () -> new SapphireItem());
	public static final RegistryObject<Item> SAPPHIRE_ORE = block(OrePlusModBlocks.SAPPHIRE_ORE);
	public static final RegistryObject<Item> SAPPHIRE_BLOCK = block(OrePlusModBlocks.SAPPHIRE_BLOCK);
	public static final RegistryObject<Item> TOPAZ = REGISTRY.register("topaz", () -> new TopazItem());
	public static final RegistryObject<Item> TOPAZ_ORE = block(OrePlusModBlocks.TOPAZ_ORE);
	public static final RegistryObject<Item> TOPAZ_BLOCK = block(OrePlusModBlocks.TOPAZ_BLOCK);
	public static final RegistryObject<Item> AQUAMARINE = REGISTRY.register("aquamarine", () -> new AquamarineItem());
	public static final RegistryObject<Item> AQUAMARINE_ORE = block(OrePlusModBlocks.AQUAMARINE_ORE);
	public static final RegistryObject<Item> AQUAMARINE_BLOCK = block(OrePlusModBlocks.AQUAMARINE_BLOCK);
	public static final RegistryObject<Item> GARNET = REGISTRY.register("garnet", () -> new GarnetItem());
	public static final RegistryObject<Item> GARNET_ORE = block(OrePlusModBlocks.GARNET_ORE);
	public static final RegistryObject<Item> GARNET_BLOCK = block(OrePlusModBlocks.GARNET_BLOCK);
	public static final RegistryObject<Item> OPAL = REGISTRY.register("opal", () -> new OpalItem());
	public static final RegistryObject<Item> OPAL_BLOCK = block(OrePlusModBlocks.OPAL_BLOCK);
	public static final RegistryObject<Item> TANZANITE = REGISTRY.register("tanzanite", () -> new TanzaniteItem());
	public static final RegistryObject<Item> TANZANITE_ORE = block(OrePlusModBlocks.TANZANITE_ORE);
	public static final RegistryObject<Item> TANZANITE_BLOCK = block(OrePlusModBlocks.TANZANITE_BLOCK);
	public static final RegistryObject<Item> MORGANITE = REGISTRY.register("morganite", () -> new MorganiteItem());
	public static final RegistryObject<Item> MORGANITE_ORE = block(OrePlusModBlocks.MORGANITE_ORE);
	public static final RegistryObject<Item> MORGANITE_BLOCK = block(OrePlusModBlocks.MORGANITE_BLOCK);
	public static final RegistryObject<Item> SULFUR_DUST = REGISTRY.register("sulfur_dust", () -> new SulfurDustItem());
	public static final RegistryObject<Item> SULFUR_ORE = block(OrePlusModBlocks.SULFUR_ORE);
	public static final RegistryObject<Item> GRAPHITE_DUST = REGISTRY.register("graphite_dust", () -> new GraphiteDustItem());
	public static final RegistryObject<Item> GRAPHITE_ORE = block(OrePlusModBlocks.GRAPHITE_ORE);
	public static final RegistryObject<Item> BAUXITE_DUST = REGISTRY.register("bauxite_dust", () -> new BauxiteDustItem());
	public static final RegistryObject<Item> BAUXITE_ORE = block(OrePlusModBlocks.BAUXITE_ORE);
	public static final RegistryObject<Item> CINNABAR_DUST = REGISTRY.register("cinnabar_dust", () -> new CinnabarDustItem());
	public static final RegistryObject<Item> CINNABAR_ORE = block(OrePlusModBlocks.CINNABAR_ORE);
	public static final RegistryObject<Item> BORAX_DUST = REGISTRY.register("borax_dust", () -> new BoraxDustItem());
	public static final RegistryObject<Item> BORAX_ORE = block(OrePlusModBlocks.BORAX_ORE);
	public static final RegistryObject<Item> GALENA_DUST = REGISTRY.register("galena_dust", () -> new GalenaDustItem());
	public static final RegistryObject<Item> GALENA_ORE = block(OrePlusModBlocks.GALENA_ORE);
	public static final RegistryObject<Item> MAGNETITE_DUST = REGISTRY.register("magnetite_dust", () -> new MagnetiteDustItem());
	public static final RegistryObject<Item> MAGNETITE_ORE = block(OrePlusModBlocks.MAGNETITE_ORE);
	public static final RegistryObject<Item> HEMATITE_DUST = REGISTRY.register("hematite_dust", () -> new HematiteDustItem());
	public static final RegistryObject<Item> HEMATITE_ORE = block(OrePlusModBlocks.HEMATITE_ORE);
	public static final RegistryObject<Item> MALACHITE_DUST = REGISTRY.register("malachite_dust", () -> new MalachiteDustItem());
	public static final RegistryObject<Item> MALACHITE_ORE = block(OrePlusModBlocks.MALACHITE_ORE);
	public static final RegistryObject<Item> AZURITE_DUST = REGISTRY.register("azurite_dust", () -> new AzuriteDustItem());
	public static final RegistryObject<Item> AZURITE_ORE = block(OrePlusModBlocks.AZURITE_ORE);
	public static final RegistryObject<Item> NEODYMIUM_INGOT = REGISTRY.register("neodymium_ingot", () -> new NeodymiumIngotItem());
	public static final RegistryObject<Item> NEODYMIUM_ORE = block(OrePlusModBlocks.NEODYMIUM_ORE);
	public static final RegistryObject<Item> NEODYMIUM_BLOCK = block(OrePlusModBlocks.NEODYMIUM_BLOCK);
	public static final RegistryObject<Item> LANTHANIUM_INGOT = REGISTRY.register("lanthanium_ingot", () -> new LanthaniumIngotItem());
	public static final RegistryObject<Item> LANTHANIUM_BLOCK = block(OrePlusModBlocks.LANTHANIUM_BLOCK);
	public static final RegistryObject<Item> CERIUM_DUST = REGISTRY.register("cerium_dust", () -> new CeriumDustItem());
	public static final RegistryObject<Item> CERIUM_ORE = block(OrePlusModBlocks.CERIUM_ORE);
	public static final RegistryObject<Item> YTTRIUM_INGOT = REGISTRY.register("yttrium_ingot", () -> new YttriumIngotItem());
	public static final RegistryObject<Item> YTTRIUM_BLOCK = block(OrePlusModBlocks.YTTRIUM_BLOCK);
	public static final RegistryObject<Item> GADOLINIUM_DUST = REGISTRY.register("gadolinium_dust", () -> new GadoliniumDustItem());
	public static final RegistryObject<Item> GADOLINIUM_ORE = block(OrePlusModBlocks.GADOLINIUM_ORE);
	public static final RegistryObject<Item> GADOLINIUM_BLOCK = block(OrePlusModBlocks.GADOLINIUM_BLOCK);
	public static final RegistryObject<Item> ALEXANDRITE = REGISTRY.register("alexandrite", () -> new AlexandriteItem());
	public static final RegistryObject<Item> ALEXANDRITE_ORE = block(OrePlusModBlocks.ALEXANDRITE_ORE);
	public static final RegistryObject<Item> ALEXANDRITE_BLOCK = block(OrePlusModBlocks.ALEXANDRITE_BLOCK);
	public static final RegistryObject<Item> PERIDOT = REGISTRY.register("peridot", () -> new PeridotItem());
	public static final RegistryObject<Item> PERIDOT_ORE = block(OrePlusModBlocks.PERIDOT_ORE);
	public static final RegistryObject<Item> PERIDOT_BLOCK = block(OrePlusModBlocks.PERIDOT_BLOCK);
	public static final RegistryObject<Item> ZIRCON_GEM = REGISTRY.register("zircon_gem", () -> new ZirconItem());
	public static final RegistryObject<Item> ZIRCON_ORE = block(OrePlusModBlocks.ZIRCON_ORE);
	public static final RegistryObject<Item> ZIRCON_BLOCK = block(OrePlusModBlocks.ZIRCON_BLOCK);
	public static final RegistryObject<Item> RHODOCHROSITE = REGISTRY.register("rhodochrosite", () -> new RhodochrositeItem());
	public static final RegistryObject<Item> RHODOCHROSITE_ORE = block(OrePlusModBlocks.RHODOCHROSITE_ORE);
	public static final RegistryObject<Item> RHODOCHROSITE_BLOCK = block(OrePlusModBlocks.RHODOCHROSITE_BLOCK);
	public static final RegistryObject<Item> FLUORITE = REGISTRY.register("fluorite", () -> new FluoriteItem());
	public static final RegistryObject<Item> FLUORITE_ORE = block(OrePlusModBlocks.FLUORITE_ORE);
	public static final RegistryObject<Item> FLUORITE_BLOCK = block(OrePlusModBlocks.FLUORITE_BLOCK);
	public static final RegistryObject<Item> TITANIUM_ARMOR_HELMET = REGISTRY.register("titanium_armor_helmet", () -> new TitaniumArmorItem.Helmet());
	public static final RegistryObject<Item> TITANIUM_ARMOR_CHESTPLATE = REGISTRY.register("titanium_armor_chestplate", () -> new TitaniumArmorItem.Chestplate());
	public static final RegistryObject<Item> TITANIUM_ARMOR_LEGGINGS = REGISTRY.register("titanium_armor_leggings", () -> new TitaniumArmorItem.Leggings());
	public static final RegistryObject<Item> TITANIUM_ARMOR_BOOTS = REGISTRY.register("titanium_armor_boots", () -> new TitaniumArmorItem.Boots());
	public static final RegistryObject<Item> TUNGSTEN_ARMOR_HELMET = REGISTRY.register("tungsten_armor_helmet", () -> new TungstenArmorItem.Helmet());
	public static final RegistryObject<Item> TUNGSTEN_ARMOR_CHESTPLATE = REGISTRY.register("tungsten_armor_chestplate", () -> new TungstenArmorItem.Chestplate());
	public static final RegistryObject<Item> TUNGSTEN_ARMOR_LEGGINGS = REGISTRY.register("tungsten_armor_leggings", () -> new TungstenArmorItem.Leggings());
	public static final RegistryObject<Item> TUNGSTEN_ARMOR_BOOTS = REGISTRY.register("tungsten_armor_boots", () -> new TungstenArmorItem.Boots());
	public static final RegistryObject<Item> PLATINUM_ARMOR_HELMET = REGISTRY.register("platinum_armor_helmet", () -> new PlatinumArmorItem.Helmet());
	public static final RegistryObject<Item> PLATINUM_ARMOR_CHESTPLATE = REGISTRY.register("platinum_armor_chestplate", () -> new PlatinumArmorItem.Chestplate());
	public static final RegistryObject<Item> PLATINUM_ARMOR_LEGGINGS = REGISTRY.register("platinum_armor_leggings", () -> new PlatinumArmorItem.Leggings());
	public static final RegistryObject<Item> PLATINUM_ARMOR_BOOTS = REGISTRY.register("platinum_armor_boots", () -> new PlatinumArmorItem.Boots());
	public static final RegistryObject<Item> COBALT_ARMOR_HELMET = REGISTRY.register("cobalt_armor_helmet", () -> new CobaltArmorItem.Helmet());
	public static final RegistryObject<Item> COBALT_ARMOR_CHESTPLATE = REGISTRY.register("cobalt_armor_chestplate", () -> new CobaltArmorItem.Chestplate());
	public static final RegistryObject<Item> COBALT_ARMOR_LEGGINGS = REGISTRY.register("cobalt_armor_leggings", () -> new CobaltArmorItem.Leggings());
	public static final RegistryObject<Item> COBALT_ARMOR_BOOTS = REGISTRY.register("cobalt_armor_boots", () -> new CobaltArmorItem.Boots());
	public static final RegistryObject<Item> CHROMIUM_ARMOR_HELMET = REGISTRY.register("chromium_armor_helmet", () -> new ChromiumArmorItem.Helmet());
	public static final RegistryObject<Item> CHROMIUM_ARMOR_CHESTPLATE = REGISTRY.register("chromium_armor_chestplate", () -> new ChromiumArmorItem.Chestplate());
	public static final RegistryObject<Item> CHROMIUM_ARMOR_LEGGINGS = REGISTRY.register("chromium_armor_leggings", () -> new ChromiumArmorItem.Leggings());
	public static final RegistryObject<Item> CHROMIUM_ARMOR_BOOTS = REGISTRY.register("chromium_armor_boots", () -> new ChromiumArmorItem.Boots());
	public static final RegistryObject<Item> RUBYGEM_ARMOR_HELMET = REGISTRY.register("rubygem_armor_helmet", () -> new RubygemArmorItem.Helmet());
	public static final RegistryObject<Item> RUBYGEM_ARMOR_CHESTPLATE = REGISTRY.register("rubygem_armor_chestplate", () -> new RubygemArmorItem.Chestplate());
	public static final RegistryObject<Item> RUBYGEM_ARMOR_LEGGINGS = REGISTRY.register("rubygem_armor_leggings", () -> new RubygemArmorItem.Leggings());
	public static final RegistryObject<Item> RUBYGEM_ARMOR_BOOTS = REGISTRY.register("rubygem_armor_boots", () -> new RubygemArmorItem.Boots());
	public static final RegistryObject<Item> GARNETGEM_ARMOR_HELMET = REGISTRY.register("garnetgem_armor_helmet", () -> new GarnetgemArmorItem.Helmet());
	public static final RegistryObject<Item> GARNETGEM_ARMOR_CHESTPLATE = REGISTRY.register("garnetgem_armor_chestplate", () -> new GarnetgemArmorItem.Chestplate());
	public static final RegistryObject<Item> GARNETGEM_ARMOR_LEGGINGS = REGISTRY.register("garnetgem_armor_leggings", () -> new GarnetgemArmorItem.Leggings());
	public static final RegistryObject<Item> GARNETGEM_ARMOR_BOOTS = REGISTRY.register("garnetgem_armor_boots", () -> new GarnetgemArmorItem.Boots());
	public static final RegistryObject<Item> TANZANITEGEM_ARMOR_HELMET = REGISTRY.register("tanzanitegem_armor_helmet", () -> new TanzanitegemArmorItem.Helmet());
	public static final RegistryObject<Item> TANZANITEGEM_ARMOR_CHESTPLATE = REGISTRY.register("tanzanitegem_armor_chestplate", () -> new TanzanitegemArmorItem.Chestplate());
	public static final RegistryObject<Item> TANZANITEGEM_ARMOR_LEGGINGS = REGISTRY.register("tanzanitegem_armor_leggings", () -> new TanzanitegemArmorItem.Leggings());
	public static final RegistryObject<Item> TANZANITEGEM_ARMOR_BOOTS = REGISTRY.register("tanzanitegem_armor_boots", () -> new TanzanitegemArmorItem.Boots());
	public static final RegistryObject<Item> NEODYMIUM_ARMOR_HELMET = REGISTRY.register("neodymium_armor_helmet", () -> new NeodymiumArmorItem.Helmet());
	public static final RegistryObject<Item> NEODYMIUM_ARMOR_CHESTPLATE = REGISTRY.register("neodymium_armor_chestplate", () -> new NeodymiumArmorItem.Chestplate());
	public static final RegistryObject<Item> NEODYMIUM_ARMOR_LEGGINGS = REGISTRY.register("neodymium_armor_leggings", () -> new NeodymiumArmorItem.Leggings());
	public static final RegistryObject<Item> NEODYMIUM_ARMOR_BOOTS = REGISTRY.register("neodymium_armor_boots", () -> new NeodymiumArmorItem.Boots());
	public static final RegistryObject<Item> YTTRIUM_ARMOR_HELMET = REGISTRY.register("yttrium_armor_helmet", () -> new YttriumArmorItem.Helmet());
	public static final RegistryObject<Item> YTTRIUM_ARMOR_CHESTPLATE = REGISTRY.register("yttrium_armor_chestplate", () -> new YttriumArmorItem.Chestplate());
	public static final RegistryObject<Item> YTTRIUM_ARMOR_LEGGINGS = REGISTRY.register("yttrium_armor_leggings", () -> new YttriumArmorItem.Leggings());
	public static final RegistryObject<Item> YTTRIUM_ARMOR_BOOTS = REGISTRY.register("yttrium_armor_boots", () -> new YttriumArmorItem.Boots());
	public static final RegistryObject<Item> ALEXANDRITEGEM_ARMOR_HELMET = REGISTRY.register("alexandritegem_armor_helmet", () -> new AlexandritegemArmorItem.Helmet());
	public static final RegistryObject<Item> ALEXANDRITEGEM_ARMOR_CHESTPLATE = REGISTRY.register("alexandritegem_armor_chestplate", () -> new AlexandritegemArmorItem.Chestplate());
	public static final RegistryObject<Item> ALEXANDRITEGEM_ARMOR_LEGGINGS = REGISTRY.register("alexandritegem_armor_leggings", () -> new AlexandritegemArmorItem.Leggings());
	public static final RegistryObject<Item> ALEXANDRITEGEM_ARMOR_BOOTS = REGISTRY.register("alexandritegem_armor_boots", () -> new AlexandritegemArmorItem.Boots());
	public static final RegistryObject<Item> ZIRCONGEM_ARMOR_HELMET = REGISTRY.register("zircongem_armor_helmet", () -> new ZircongemArmorItem.Helmet());
	public static final RegistryObject<Item> ZIRCONGEM_ARMOR_CHESTPLATE = REGISTRY.register("zircongem_armor_chestplate", () -> new ZircongemArmorItem.Chestplate());
	public static final RegistryObject<Item> ZIRCONGEM_ARMOR_LEGGINGS = REGISTRY.register("zircongem_armor_leggings", () -> new ZircongemArmorItem.Leggings());
	public static final RegistryObject<Item> ZIRCONGEM_ARMOR_BOOTS = REGISTRY.register("zircongem_armor_boots", () -> new ZircongemArmorItem.Boots());
	public static final RegistryObject<Item> TITANIUM_PICKAXE = REGISTRY.register("titanium_pickaxe", () -> new TitaniumPickaxeItem());
	public static final RegistryObject<Item> TITANIUM_AXE = REGISTRY.register("titanium_axe", () -> new TitaniumAxeItem());
	public static final RegistryObject<Item> TITANIUM_SWORD = REGISTRY.register("titanium_sword", () -> new TitaniumSwordItem());
	public static final RegistryObject<Item> TITANIUM_SHOVEL = REGISTRY.register("titanium_shovel", () -> new TitaniumShovelItem());
	public static final RegistryObject<Item> TITANIUM_HOE = REGISTRY.register("titanium_hoe", () -> new TitaniumHoeItem());
	public static final RegistryObject<Item> TUNGSTEN_PICKAXE = REGISTRY.register("tungsten_pickaxe", () -> new TungstenPickaxeItem());
	public static final RegistryObject<Item> TUNGSTEN_AXE = REGISTRY.register("tungsten_axe", () -> new TungstenAxeItem());
	public static final RegistryObject<Item> TUNGSTEN_SWORD = REGISTRY.register("tungsten_sword", () -> new TungstenSwordItem());
	public static final RegistryObject<Item> TUNGSTEN_SHOVEL = REGISTRY.register("tungsten_shovel", () -> new TungstenShovelItem());
	public static final RegistryObject<Item> TUNGSTEN_HOE = REGISTRY.register("tungsten_hoe", () -> new TungstenHoeItem());
	public static final RegistryObject<Item> COBALT_PICKAXE = REGISTRY.register("cobalt_pickaxe", () -> new CobaltPickaxeItem());
	public static final RegistryObject<Item> COBALT_AXE = REGISTRY.register("cobalt_axe", () -> new CobaltAxeItem());
	public static final RegistryObject<Item> COBALT_SWORD = REGISTRY.register("cobalt_sword", () -> new CobaltSwordItem());
	public static final RegistryObject<Item> COBALT_SHOVEL = REGISTRY.register("cobalt_shovel", () -> new CobaltShovelItem());
	public static final RegistryObject<Item> COBALT_HOE = REGISTRY.register("cobalt_hoe", () -> new CobaltHoeItem());
	public static final RegistryObject<Item> PLATINUM_PICKAXE = REGISTRY.register("platinum_pickaxe", () -> new PlatinumPickaxeItem());
	public static final RegistryObject<Item> PLATINUM_AXE = REGISTRY.register("platinum_axe", () -> new PlatinumAxeItem());
	public static final RegistryObject<Item> PLATINUM_SWORD = REGISTRY.register("platinum_sword", () -> new PlatinumSwordItem());
	public static final RegistryObject<Item> PLATINUM_SHOVEL = REGISTRY.register("platinum_shovel", () -> new PlatinumShovelItem());
	public static final RegistryObject<Item> PLATINUM_HOE = REGISTRY.register("platinum_hoe", () -> new PlatinumHoeItem());
	public static final RegistryObject<Item> SILVER_PICKAXE = REGISTRY.register("silver_pickaxe", () -> new SilverPickaxeItem());
	public static final RegistryObject<Item> SILVER_AXE = REGISTRY.register("silver_axe", () -> new SilverAxeItem());
	public static final RegistryObject<Item> SILVER_SWORD = REGISTRY.register("silver_sword", () -> new SilverSwordItem());
	public static final RegistryObject<Item> SILVER_SHOVEL = REGISTRY.register("silver_shovel", () -> new SilverShovelItem());
	public static final RegistryObject<Item> SILVER_HOE = REGISTRY.register("silver_hoe", () -> new SilverHoeItem());
	public static final RegistryObject<Item> NICKEL_PICKAXE = REGISTRY.register("nickel_pickaxe", () -> new NickelPickaxeItem());
	public static final RegistryObject<Item> NICKEL_AXE = REGISTRY.register("nickel_axe", () -> new NickelAxeItem());
	public static final RegistryObject<Item> NICKEL_SWORD = REGISTRY.register("nickel_sword", () -> new NickelSwordItem());
	public static final RegistryObject<Item> NICKEL_SHOVEL = REGISTRY.register("nickel_shovel", () -> new NickelShovelItem());
	public static final RegistryObject<Item> NICKEL_HOE = REGISTRY.register("nickel_hoe", () -> new NickelHoeItem());
	public static final RegistryObject<Item> RUBYGEM_PICKAXE = REGISTRY.register("rubygem_pickaxe", () -> new RubygemPickaxeItem());
	public static final RegistryObject<Item> RUBYGEM_AXE = REGISTRY.register("rubygem_axe", () -> new RubygemAxeItem());
	public static final RegistryObject<Item> RUBYGEM_SWORD = REGISTRY.register("rubygem_sword", () -> new RubygemSwordItem());
	public static final RegistryObject<Item> RUBYGEM_SHOVEL = REGISTRY.register("rubygem_shovel", () -> new RubygemShovelItem());
	public static final RegistryObject<Item> RUBYGEM_HOE = REGISTRY.register("rubygem_hoe", () -> new RubygemHoeItem());
	public static final RegistryObject<Item> SAPPHIREGEM_PICKAXE = REGISTRY.register("sapphiregem_pickaxe", () -> new SapphiregemPickaxeItem());
	public static final RegistryObject<Item> SAPPHIREGEM_AXE = REGISTRY.register("sapphiregem_axe", () -> new SapphiregemAxeItem());
	public static final RegistryObject<Item> SAPPHIREGEM_SWORD = REGISTRY.register("sapphiregem_sword", () -> new SapphiregemSwordItem());
	public static final RegistryObject<Item> SAPPHIREGEM_SHOVEL = REGISTRY.register("sapphiregem_shovel", () -> new SapphiregemShovelItem());
	public static final RegistryObject<Item> SAPPHIREGEM_HOE = REGISTRY.register("sapphiregem_hoe", () -> new SapphiregemHoeItem());
	public static final RegistryObject<Item> TOPAZGEM_PICKAXE = REGISTRY.register("topazgem_pickaxe", () -> new TopazgemPickaxeItem());
	public static final RegistryObject<Item> TOPAZGEM_AXE = REGISTRY.register("topazgem_axe", () -> new TopazgemAxeItem());
	public static final RegistryObject<Item> TOPAZGEM_SWORD = REGISTRY.register("topazgem_sword", () -> new TopazgemSwordItem());
	public static final RegistryObject<Item> TOPAZGEM_SHOVEL = REGISTRY.register("topazgem_shovel", () -> new TopazgemShovelItem());
	public static final RegistryObject<Item> TOPAZGEM_HOE = REGISTRY.register("topazgem_hoe", () -> new TopazgemHoeItem());
	public static final RegistryObject<Item> GARNETGEM_PICKAXE = REGISTRY.register("garnetgem_pickaxe", () -> new GarnetgemPickaxeItem());
	public static final RegistryObject<Item> GARNETGEM_AXE = REGISTRY.register("garnetgem_axe", () -> new GarnetgemAxeItem());
	public static final RegistryObject<Item> GARNETGEM_SWORD = REGISTRY.register("garnetgem_sword", () -> new GarnetgemSwordItem());
	public static final RegistryObject<Item> GARNETGEM_SHOVEL = REGISTRY.register("garnetgem_shovel", () -> new GarnetgemShovelItem());
	public static final RegistryObject<Item> GARNETGEM_HOE = REGISTRY.register("garnetgem_hoe", () -> new GarnetgemHoeItem());
	public static final RegistryObject<Item> NEODYMIUM_PICKAXE = REGISTRY.register("neodymium_pickaxe", () -> new NeodymiumPickaxeItem());
	public static final RegistryObject<Item> NEODYMIUM_AXE = REGISTRY.register("neodymium_axe", () -> new NeodymiumAxeItem());
	public static final RegistryObject<Item> NEODYMIUM_SWORD = REGISTRY.register("neodymium_sword", () -> new NeodymiumSwordItem());
	public static final RegistryObject<Item> NEODYMIUM_SHOVEL = REGISTRY.register("neodymium_shovel", () -> new NeodymiumShovelItem());
	public static final RegistryObject<Item> NEODYMIUM_HOE = REGISTRY.register("neodymium_hoe", () -> new NeodymiumHoeItem());
	public static final RegistryObject<Item> YTTRIUM_PICKAXE = REGISTRY.register("yttrium_pickaxe", () -> new YttriumPickaxeItem());
	public static final RegistryObject<Item> YTTRIUM_AXE = REGISTRY.register("yttrium_axe", () -> new YttriumAxeItem());
	public static final RegistryObject<Item> YTTRIUM_SWORD = REGISTRY.register("yttrium_sword", () -> new YttriumSwordItem());
	public static final RegistryObject<Item> YTTRIUM_SHOVEL = REGISTRY.register("yttrium_shovel", () -> new YttriumShovelItem());
	public static final RegistryObject<Item> YTTRIUM_HOE = REGISTRY.register("yttrium_hoe", () -> new YttriumHoeItem());
	public static final RegistryObject<Item> ZIRCONGEM_PICKAXE = REGISTRY.register("zircongem_pickaxe", () -> new ZircongemPickaxeItem());
	public static final RegistryObject<Item> ZIRCONGEM_AXE = REGISTRY.register("zircongem_axe", () -> new ZircongemAxeItem());
	public static final RegistryObject<Item> ZIRCONGEM_SWORD = REGISTRY.register("zircongem_sword", () -> new ZircongemSwordItem());
	public static final RegistryObject<Item> ZIRCONGEM_SHOVEL = REGISTRY.register("zircongem_shovel", () -> new ZircongemShovelItem());
	public static final RegistryObject<Item> ZIRCONGEM_HOE = REGISTRY.register("zircongem_hoe", () -> new ZircongemHoeItem());
	public static final RegistryObject<Item> GADOLINIUMINGOT = REGISTRY.register("gadoliniumingot", () -> new GadoliniumingotItem());
	public static final RegistryObject<Item> GADOLINIUM_PICKAXE = REGISTRY.register("gadolinium_pickaxe", () -> new GadoliniumPickaxeItem());
	public static final RegistryObject<Item> GADOLINIUM_AXE = REGISTRY.register("gadolinium_axe", () -> new GadoliniumAxeItem());
	public static final RegistryObject<Item> GADOLINIUM_SWORD = REGISTRY.register("gadolinium_sword", () -> new GadoliniumSwordItem());
	public static final RegistryObject<Item> GADOLINIUM_SHOVEL = REGISTRY.register("gadolinium_shovel", () -> new GadoliniumShovelItem());
	public static final RegistryObject<Item> GADOLINIUM_HOE = REGISTRY.register("gadolinium_hoe", () -> new GadoliniumHoeItem());
	public static final RegistryObject<Item> BRONZE = REGISTRY.register("bronze", () -> new BronzeItem());
	public static final RegistryObject<Item> BRASS = REGISTRY.register("brass", () -> new BrassItem());
	public static final RegistryObject<Item> STEEL = REGISTRY.register("steel", () -> new SteelItem());
	public static final RegistryObject<Item> ELECTRUM = REGISTRY.register("electrum", () -> new ElectrumItem());
	public static final RegistryObject<Item> ROSE_GOLD = REGISTRY.register("rose_gold", () -> new RoseGoldItem());
	public static final RegistryObject<Item> TIN = REGISTRY.register("tin", () -> new TinItem());
	public static final RegistryObject<Item> CARBON = REGISTRY.register("carbon", () -> new CarbonItem());
	public static final RegistryObject<Item> ZINC = REGISTRY.register("zinc", () -> new ZincItem());
	public static final RegistryObject<Item> METAL_SCRAP = REGISTRY.register("metal_scrap", () -> new MetalScrapItem());
	public static final RegistryObject<Item> ROSE_GOLD_PICKAXE = REGISTRY.register("rose_gold_pickaxe", () -> new RosePickaxeItem());
	public static final RegistryObject<Item> ROSE_GOLD_AXE = REGISTRY.register("rose_gold_axe", () -> new RoseAxeItem());
	public static final RegistryObject<Item> ROSE_GOLD_SWORD = REGISTRY.register("rose_gold_sword", () -> new RoseSwordItem());
	public static final RegistryObject<Item> ROSE_GOLD_SHOVEL = REGISTRY.register("rose_gold_shovel", () -> new RoseShovelItem());
	public static final RegistryObject<Item> ROSE_GOLD_HOE = REGISTRY.register("rose_gold_hoe", () -> new RoseHoeItem());
	public static final RegistryObject<Item> ROSE_GOLD_ARMOR_HELMET = REGISTRY.register("rose_gold_armor_helmet", () -> new RoseGoldIngotArmorItem.Helmet());
	public static final RegistryObject<Item> ROSE_GOLD_ARMOR_CHESTPLATE = REGISTRY.register("rose_gold_armor_chestplate", () -> new RoseGoldIngotArmorItem.Chestplate());
	public static final RegistryObject<Item> ROSE_GOLD_ARMOR_LEGGINGS = REGISTRY.register("rose_gold_armor_leggings", () -> new RoseGoldIngotArmorItem.Leggings());
	public static final RegistryObject<Item> ROSE_GOLD_ARMOR_BOOTS = REGISTRY.register("rose_gold_armor_boots", () -> new RoseGoldIngotArmorItem.Boots());
	public static final RegistryObject<Item> ELECTRUM_INGOT_ARMOR_HELMET = REGISTRY.register("electrum_ingot_armor_helmet", () -> new Electrum_IngotArmorItem.Helmet());
	public static final RegistryObject<Item> ELECTRUM_INGOT_ARMOR_CHESTPLATE = REGISTRY.register("electrum_ingot_armor_chestplate", () -> new Electrum_IngotArmorItem.Chestplate());
	public static final RegistryObject<Item> ELECTRUM_INGOT_ARMOR_LEGGINGS = REGISTRY.register("electrum_ingot_armor_leggings", () -> new Electrum_IngotArmorItem.Leggings());
	public static final RegistryObject<Item> ELECTRUM_INGOT_ARMOR_BOOTS = REGISTRY.register("electrum_ingot_armor_boots", () -> new Electrum_IngotArmorItem.Boots());
	public static final RegistryObject<Item> ALLOY_FURNACE = block(OrePlusModBlocks.ALLOY_FURNACE);
	public static final RegistryObject<Item> ADAMANTITE = REGISTRY.register("adamantite", () -> new AdamantiteItem());
	public static final RegistryObject<Item> ORICHALCUM = REGISTRY.register("orichalcum", () -> new OrichalcumItem());
	public static final RegistryObject<Item> MITHRIL = REGISTRY.register("mithril", () -> new MithrilItem());
	public static final RegistryObject<Item> CELESTIUM = REGISTRY.register("celestium", () -> new CelestiumItem());
	public static final RegistryObject<Item> VOIDSTONE = REGISTRY.register("voidstone", () -> new VoidstoneItem());
	public static final RegistryObject<Item> AETHERIUM = REGISTRY.register("aetherium", () -> new AetheriumItem());
	public static final RegistryObject<Item> ADAMANTITE_DUST = REGISTRY.register("adamantite_dust", () -> new AdamantiteDustItem());
	public static final RegistryObject<Item> ADAMANTITE_ORE = block(OrePlusModBlocks.ADAMANTITE_ORE);
	public static final RegistryObject<Item> CELESTIUM_ORE = block(OrePlusModBlocks.CELESTIUM_ORE, new Item.Properties().rarity(Rarity.EPIC));
	public static final RegistryObject<Item> VOIDSTONE_ORE = block(OrePlusModBlocks.VOIDSTONE_ORE, new Item.Properties().rarity(Rarity.EPIC));
	public static final RegistryObject<Item> CELESTIUM_PICKAXE = REGISTRY.register("celestium_pickaxe", () -> new CelestiumPickaxeItem());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_ARMOR_HELMET = REGISTRY.register("aquamarine_armor_armor_helmet", () -> new AquamarineArmorArmorItem.Helmet());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_ARMOR_CHESTPLATE = REGISTRY.register("aquamarine_armor_armor_chestplate", () -> new AquamarineArmorArmorItem.Chestplate());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_ARMOR_LEGGINGS = REGISTRY.register("aquamarine_armor_armor_leggings", () -> new AquamarineArmorArmorItem.Leggings());
	public static final RegistryObject<Item> AQUAMARINE_ARMOR_ARMOR_BOOTS = REGISTRY.register("aquamarine_armor_armor_boots", () -> new AquamarineArmorArmorItem.Boots());
	public static final RegistryObject<Item> OPAL_GEM_ARMOR_HELMET = REGISTRY.register("opal_gem_armor_helmet", () -> new OpalGemArmorItem.Helmet());
	public static final RegistryObject<Item> OPAL_GEM_ARMOR_CHESTPLATE = REGISTRY.register("opal_gem_armor_chestplate", () -> new OpalGemArmorItem.Chestplate());
	public static final RegistryObject<Item> OPAL_GEM_ARMOR_LEGGINGS = REGISTRY.register("opal_gem_armor_leggings", () -> new OpalGemArmorItem.Leggings());
	public static final RegistryObject<Item> OPAL_GEM_ARMOR_BOOTS = REGISTRY.register("opal_gem_armor_boots", () -> new OpalGemArmorItem.Boots());
	public static final RegistryObject<Item> PALLADIUM_SWORD = REGISTRY.register("palladium_sword", () -> new PalladiumSwordItem());
	public static final RegistryObject<Item> PALLADIUM_PICKAXE = REGISTRY.register("palladium_pickaxe", () -> new PalladiumPickaxeItem());
	public static final RegistryObject<Item> PALLADIUM_AXE = REGISTRY.register("palladium_axe", () -> new PalladiumAxeItem());
	public static final RegistryObject<Item> PALLADIUM_HOE = REGISTRY.register("palladium_hoe", () -> new PalladiumHoeItem());
	public static final RegistryObject<Item> PALLADIUM_SHOVEL = REGISTRY.register("palladium_shovel", () -> new PalladiumShovelItem());
	public static final RegistryObject<Item> LANTHANIUM_SWORD = REGISTRY.register("lanthanium_sword", () -> new LanthaniumSwordItem());
	public static final RegistryObject<Item> LANTHANIUM_PICKAXE = REGISTRY.register("lanthanium_pickaxe", () -> new LanthaniumPickaxeItem());
	public static final RegistryObject<Item> LANTHANIUM_AXE = REGISTRY.register("lanthanium_axe", () -> new LanthaniumAxeItem());
	public static final RegistryObject<Item> LANTHANIUM_SHOVEL = REGISTRY.register("lanthanium_shovel", () -> new LanthaniumShovelItem());
	public static final RegistryObject<Item> LANTHANIUM_HOE = REGISTRY.register("lanthanium_hoe", () -> new LanthaniumHoeItem());
	public static final RegistryObject<Item> PERIDOT_SWORD = REGISTRY.register("peridot_sword", () -> new PeridotSwordItem());
	public static final RegistryObject<Item> PERIDOT_PICKAXE = REGISTRY.register("peridot_pickaxe", () -> new PeridotPickaxeItem());
	public static final RegistryObject<Item> PERIDOT_AXE = REGISTRY.register("peridot_axe", () -> new PeridotAxeItem());
	public static final RegistryObject<Item> PERIDOT_SHOVEL = REGISTRY.register("peridot_shovel", () -> new PeridotShovelItem());
	public static final RegistryObject<Item> PERIDOT_HOE = REGISTRY.register("peridot_hoe", () -> new PeridotHoeItem());
	public static final RegistryObject<Item> PALLADIUM_HELMET = REGISTRY.register("palladium_helmet", () -> new PalladiumItem.Helmet());
	public static final RegistryObject<Item> PALLADIUM_CHESTPLATE = REGISTRY.register("palladium_chestplate", () -> new PalladiumItem.Chestplate());
	public static final RegistryObject<Item> PALLADIUM_LEGGINGS = REGISTRY.register("palladium_leggings", () -> new PalladiumItem.Leggings());
	public static final RegistryObject<Item> PALLADIUM_BOOTS = REGISTRY.register("palladium_boots", () -> new PalladiumItem.Boots());
	public static final RegistryObject<Item> LANTHANIUM_HELMET = REGISTRY.register("lanthanium_helmet", () -> new LanthaniumItem.Helmet());
	public static final RegistryObject<Item> LANTHANIUM_CHESTPLATE = REGISTRY.register("lanthanium_chestplate", () -> new LanthaniumItem.Chestplate());
	public static final RegistryObject<Item> LANTHANIUM_LEGGINGS = REGISTRY.register("lanthanium_leggings", () -> new LanthaniumItem.Leggings());
	public static final RegistryObject<Item> LANTHANIUM_BOOTS = REGISTRY.register("lanthanium_boots", () -> new LanthaniumItem.Boots());
	public static final RegistryObject<Item> PERIDOT_ARMOR_HELMET = REGISTRY.register("peridot_armor_helmet", () -> new PeridotArmorItem.Helmet());
	public static final RegistryObject<Item> PERIDOT_ARMOR_CHESTPLATE = REGISTRY.register("peridot_armor_chestplate", () -> new PeridotArmorItem.Chestplate());
	public static final RegistryObject<Item> PERIDOT_ARMOR_LEGGINGS = REGISTRY.register("peridot_armor_leggings", () -> new PeridotArmorItem.Leggings());
	public static final RegistryObject<Item> PERIDOT_ARMOR_BOOTS = REGISTRY.register("peridot_armor_boots", () -> new PeridotArmorItem.Boots());
	public static final RegistryObject<Item> RHODOCHROSITE_ARMOR_HELMET = REGISTRY.register("rhodochrosite_armor_helmet", () -> new RhodochrositeArmorItem.Helmet());
	public static final RegistryObject<Item> RHODOCHROSITE_ARMOR_CHESTPLATE = REGISTRY.register("rhodochrosite_armor_chestplate", () -> new RhodochrositeArmorItem.Chestplate());
	public static final RegistryObject<Item> RHODOCHROSITE_ARMOR_LEGGINGS = REGISTRY.register("rhodochrosite_armor_leggings", () -> new RhodochrositeArmorItem.Leggings());
	public static final RegistryObject<Item> RHODOCHROSITE_ARMOR_BOOTS = REGISTRY.register("rhodochrosite_armor_boots", () -> new RhodochrositeArmorItem.Boots());
	public static final RegistryObject<Item> FLUORITE_ARMOR_HELMET = REGISTRY.register("fluorite_armor_helmet", () -> new FluoriteArmorItem.Helmet());
	public static final RegistryObject<Item> FLUORITE_ARMOR_CHESTPLATE = REGISTRY.register("fluorite_armor_chestplate", () -> new FluoriteArmorItem.Chestplate());
	public static final RegistryObject<Item> FLUORITE_ARMOR_LEGGINGS = REGISTRY.register("fluorite_armor_leggings", () -> new FluoriteArmorItem.Leggings());
	public static final RegistryObject<Item> FLUORITE_ARMOR_BOOTS = REGISTRY.register("fluorite_armor_boots", () -> new FluoriteArmorItem.Boots());
	public static final RegistryObject<Item> CARBON_BLOCK = block(OrePlusModBlocks.CARBON_BLOCK, new Item.Properties().rarity(Rarity.UNCOMMON));
	public static final RegistryObject<Item> VOID_LEAK = REGISTRY.register("void_leak", () -> new VoidLeakItem());
	public static final RegistryObject<Item> VOID_TOOL = REGISTRY.register("void_tool", () -> new VoidToolItem());
	public static final RegistryObject<Item> DEEPSLATE_TUNGSTEN_ORE = block(OrePlusModBlocks.DEEPSLATE_TUNGSTEN_ORE);
	public static final RegistryObject<Item> DEEPSLATE_PALLADIUM_ORE = block(OrePlusModBlocks.DEEPSLATE_PALLADIUM_ORE);
	public static final RegistryObject<Item> DEEPSLATE_GRAPHITE_ORE = block(OrePlusModBlocks.DEEPSLATE_GRAPHITE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_CINNABAR_ORE = block(OrePlusModBlocks.DEEPSLATE_CINNABAR_ORE);
	public static final RegistryObject<Item> DEEPSLATE_BORAX_ORE = block(OrePlusModBlocks.DEEPSLATE_BORAX_ORE);
	public static final RegistryObject<Item> DEEPSLATE_GALENA_ORE = block(OrePlusModBlocks.DEEPSLATE_GALENA_ORE);
	public static final RegistryObject<Item> DEEPSLATE_MAGNETITE_ORE = block(OrePlusModBlocks.DEEPSLATE_MAGNETITE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_MALACHITE_ORE = block(OrePlusModBlocks.DEEPSLATE_MALACHITE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_AZURITE_ORE = block(OrePlusModBlocks.DEEPSLATE_AZURITE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_NEODYMIUM_ORE = block(OrePlusModBlocks.DEEPSLATE_NEODYMIUM_ORE);
	public static final RegistryObject<Item> DEEPSLATE_CERIUM_ORE = block(OrePlusModBlocks.DEEPSLATE_CERIUM_ORE);
	public static final RegistryObject<Item> DEEPSLATE_GADOLINIUM_ORE = block(OrePlusModBlocks.DEEPSLATE_GADOLINIUM_ORE);
	public static final RegistryObject<Item> DEEPSLATE_SILVER_ORE = block(OrePlusModBlocks.DEEPSLATE_SILVER_ORE);
	public static final RegistryObject<Item> DEEPSLATE_PLATINUM_ORE = block(OrePlusModBlocks.DEEPSLATE_PLATINUM_ORE);
	public static final RegistryObject<Item> DEEPSLATE_COBALT_ORE = block(OrePlusModBlocks.DEEPSLATE_COBALT_ORE);
	public static final RegistryObject<Item> DEEPSLATE_NICKEL_ORE = block(OrePlusModBlocks.DEEPSLATE_NICKEL_ORE);
	public static final RegistryObject<Item> DEEPSLATE_BAUXITE_ORE = block(OrePlusModBlocks.DEEPSLATE_BAUXITE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_RUBY_ORE = block(OrePlusModBlocks.DEEPSLATE_RUBY_ORE);
	public static final RegistryObject<Item> DEEPSLATE_SAPPHIRE_ORE = block(OrePlusModBlocks.DEEPSLATE_SAPPHIRE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_TOPAZ_ORE = block(OrePlusModBlocks.DEEPSLATE_TOPAZ_ORE);
	public static final RegistryObject<Item> DEEPSLATE_AQUAMARINE_ORE = block(OrePlusModBlocks.DEEPSLATE_AQUAMARINE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_GARNET_ORE = block(OrePlusModBlocks.DEEPSLATE_GARNET_ORE);
	public static final RegistryObject<Item> DEEPSLATE_TANZANITE_ORE = block(OrePlusModBlocks.DEEPSLATE_TANZANITE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_MORGANITE_ORE = block(OrePlusModBlocks.DEEPSLATE_MORGANITE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_ALEXANDRITE_ORE = block(OrePlusModBlocks.DEEPSLATE_ALEXANDRITE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_PERIDOT_ORE = block(OrePlusModBlocks.DEEPSLATE_PERIDOT_ORE);
	public static final RegistryObject<Item> DEEPSLATE_ZIRCON_ORE = block(OrePlusModBlocks.DEEPSLATE_ZIRCON_ORE);
	public static final RegistryObject<Item> DEEPSLATE_RHODOCHROSITE_ORE = block(OrePlusModBlocks.DEEPSLATE_RHODOCHROSITE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_FLUORITE_ORE = block(OrePlusModBlocks.DEEPSLATE_FLUORITE_ORE);
	public static final RegistryObject<Item> DEEPSLATE_VOIDSTONE_ORE = block(OrePlusModBlocks.DEEPSLATE_VOIDSTONE_ORE, new Item.Properties().rarity(Rarity.EPIC));
	public static final RegistryObject<Item> DEEPSLATE_HEMATITE_ORE = block(OrePlusModBlocks.DEEPSLATE_HEMATITE_ORE);
	public static final RegistryObject<Item> MORGANITE_ARMOR_HELMET = REGISTRY.register("morganite_armor_helmet", () -> new MorganiteArmorItem.Helmet());
	public static final RegistryObject<Item> MORGANITE_ARMOR_CHESTPLATE = REGISTRY.register("morganite_armor_chestplate", () -> new MorganiteArmorItem.Chestplate());
	public static final RegistryObject<Item> MORGANITE_ARMOR_LEGGINGS = REGISTRY.register("morganite_armor_leggings", () -> new MorganiteArmorItem.Leggings());
	public static final RegistryObject<Item> MORGANITE_ARMOR_BOOTS = REGISTRY.register("morganite_armor_boots", () -> new MorganiteArmorItem.Boots());
	public static final RegistryObject<Item> OPAL_SWORD = REGISTRY.register("opal_sword", () -> new OpalSwordItem());
	public static final RegistryObject<Item> OPAL_PICKAXE = REGISTRY.register("opal_pickaxe", () -> new OpalPickaxeItem());
	public static final RegistryObject<Item> OPAL_AXE = REGISTRY.register("opal_axe", () -> new OpalAxeItem());
	public static final RegistryObject<Item> OPAL_SHOVEL = REGISTRY.register("opal_shovel", () -> new OpalShovelItem());
	public static final RegistryObject<Item> OPAL_HOE = REGISTRY.register("opal_hoe", () -> new OpalHoeItem());
	public static final RegistryObject<Item> ADAMANTITE_SWORD = REGISTRY.register("adamantite_sword", () -> new AdamantiteSwordItem());
	public static final RegistryObject<Item> ADAMANTITE_PICKAXE = REGISTRY.register("adamantite_pickaxe", () -> new AdamantitePickaxeItem());
	public static final RegistryObject<Item> ADAMANTITE_AXE = REGISTRY.register("adamantite_axe", () -> new AdamantiteAxeItem());
	public static final RegistryObject<Item> ADAMANTITE_SHOVEL = REGISTRY.register("adamantite_shovel", () -> new AdamantiteShovelItem());
	public static final RegistryObject<Item> ADAMANTITE_HOE = REGISTRY.register("adamantite_hoe", () -> new AdamantiteHoeItem());
	public static final RegistryObject<Item> ORICHALCUM_SWORD = REGISTRY.register("orichalcum_sword", () -> new OrichalcumSwordItem());
	public static final RegistryObject<Item> ORICHALCUM_PICKAXE = REGISTRY.register("orichalcum_pickaxe", () -> new OrichalcumPickaxeItem());
	public static final RegistryObject<Item> ORICHALCUM_AXE = REGISTRY.register("orichalcum_axe", () -> new OrichalcumAxeItem());
	public static final RegistryObject<Item> ORICHALCUM_SHOVEL = REGISTRY.register("orichalcum_shovel", () -> new OrichalcumShovelItem());
	public static final RegistryObject<Item> ORICHALCUM_HOE = REGISTRY.register("orichalcum_hoe", () -> new OrichalcumHoeItem());
	public static final RegistryObject<Item> BRASS_SWORD = REGISTRY.register("brass_sword", () -> new BrassSwordItem());
	public static final RegistryObject<Item> BRASS_PICKAXE = REGISTRY.register("brass_pickaxe", () -> new BrassPickaxeItem());
	public static final RegistryObject<Item> BRASS_AXE = REGISTRY.register("brass_axe", () -> new BrassAxeItem());
	public static final RegistryObject<Item> BRASS_SHOVEL = REGISTRY.register("brass_shovel", () -> new BrassShovelItem());
	public static final RegistryObject<Item> BRASS_HOE = REGISTRY.register("brass_hoe", () -> new BrassHoeItem());
	public static final RegistryObject<Item> ELECTRUM_SWORD = REGISTRY.register("electrum_sword", () -> new ElectrumSwordItem());
	public static final RegistryObject<Item> ELECTRUM_PICKAXE = REGISTRY.register("electrum_pickaxe", () -> new ElectrumPickaxeItem());
	public static final RegistryObject<Item> ELECTRUM_AXE = REGISTRY.register("electrum_axe", () -> new ElectrumAxeItem());
	public static final RegistryObject<Item> ELECTRUM_SHOVEL = REGISTRY.register("electrum_shovel", () -> new ElectrumShovelItem());
	public static final RegistryObject<Item> ELECTRUM_HOE = REGISTRY.register("electrum_hoe", () -> new ElectrumHoeItem());
	public static final RegistryObject<Item> MITHRIL_SWORD = REGISTRY.register("mithril_sword", () -> new MithrilSwordItem());
	public static final RegistryObject<Item> MITHRIL_PICKAXE = REGISTRY.register("mithril_pickaxe", () -> new MithrilPickaxeItem());
	public static final RegistryObject<Item> MITHRIL_AXE = REGISTRY.register("mithril_axe", () -> new MithrilAxeItem());
	public static final RegistryObject<Item> MITHRIL_SHOVEL = REGISTRY.register("mithril_shovel", () -> new MithrilShovelItem());
	public static final RegistryObject<Item> MITHRIL_HOE = REGISTRY.register("mithril_hoe", () -> new MithrilHoeItem());
	public static final RegistryObject<Item> ORICHALCUM_ARMOR_HELMET = REGISTRY.register("orichalcum_armor_helmet", () -> new OrichalcumArmorItem.Helmet());
	public static final RegistryObject<Item> ORICHALCUM_ARMOR_CHESTPLATE = REGISTRY.register("orichalcum_armor_chestplate", () -> new OrichalcumArmorItem.Chestplate());
	public static final RegistryObject<Item> ORICHALCUM_ARMOR_LEGGINGS = REGISTRY.register("orichalcum_armor_leggings", () -> new OrichalcumArmorItem.Leggings());
	public static final RegistryObject<Item> ORICHALCUM_ARMOR_BOOTS = REGISTRY.register("orichalcum_armor_boots", () -> new OrichalcumArmorItem.Boots());
	public static final RegistryObject<Item> BRASS_ARMOR_HELMET = REGISTRY.register("brass_armor_helmet", () -> new BrassArmorItem.Helmet());
	public static final RegistryObject<Item> BRASS_ARMOR_CHESTPLATE = REGISTRY.register("brass_armor_chestplate", () -> new BrassArmorItem.Chestplate());
	public static final RegistryObject<Item> BRASS_ARMOR_LEGGINGS = REGISTRY.register("brass_armor_leggings", () -> new BrassArmorItem.Leggings());
	public static final RegistryObject<Item> BRASS_ARMOR_BOOTS = REGISTRY.register("brass_armor_boots", () -> new BrassArmorItem.Boots());
	public static final RegistryObject<Item> MITHRIL_ARMOR_HELMET = REGISTRY.register("mithril_armor_helmet", () -> new MithrilArmorItem.Helmet());
	public static final RegistryObject<Item> MITHRIL_ARMOR_CHESTPLATE = REGISTRY.register("mithril_armor_chestplate", () -> new MithrilArmorItem.Chestplate());
	public static final RegistryObject<Item> MITHRIL_ARMOR_LEGGINGS = REGISTRY.register("mithril_armor_leggings", () -> new MithrilArmorItem.Leggings());
	public static final RegistryObject<Item> MITHRIL_ARMOR_BOOTS = REGISTRY.register("mithril_armor_boots", () -> new MithrilArmorItem.Boots());
	public static final RegistryObject<Item> STEEL_SWORD = REGISTRY.register("steel_sword", () -> new SteelSwordItem());
	public static final RegistryObject<Item> STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", () -> new SteelPickaxeItem());
	public static final RegistryObject<Item> STEEL_AXE = REGISTRY.register("steel_axe", () -> new SteelAxeItem());
	public static final RegistryObject<Item> STEEL_SHOVEL = REGISTRY.register("steel_shovel", () -> new SteelShovelItem());
	public static final RegistryObject<Item> STEEL_HOE = REGISTRY.register("steel_hoe", () -> new SteelHoeItem());
	public static final RegistryObject<Item> STEEL_ARMOR_HELMET = REGISTRY.register("steel_armor_helmet", () -> new SteelArmorItem.Helmet());
	public static final RegistryObject<Item> STEEL_ARMOR_CHESTPLATE = REGISTRY.register("steel_armor_chestplate", () -> new SteelArmorItem.Chestplate());
	public static final RegistryObject<Item> STEEL_ARMOR_LEGGINGS = REGISTRY.register("steel_armor_leggings", () -> new SteelArmorItem.Leggings());
	public static final RegistryObject<Item> STEEL_ARMOR_BOOTS = REGISTRY.register("steel_armor_boots", () -> new SteelArmorItem.Boots());
	public static final RegistryObject<Item> TIN_ORE = block(OrePlusModBlocks.TIN_ORE);
	public static final RegistryObject<Item> DEEPSLATE_TIN_ORE = block(OrePlusModBlocks.DEEPSLATE_TIN_ORE);
	public static final RegistryObject<Item> TIN_DUST = REGISTRY.register("tin_dust", () -> new TinDustItem());
	public static final RegistryObject<Item> TIN_BLOCK = block(OrePlusModBlocks.TIN_BLOCK);
	public static final RegistryObject<Item> ZINC_ORE = block(OrePlusModBlocks.ZINC_ORE);
	public static final RegistryObject<Item> DEEPSLATE_ZINC_ORE = block(OrePlusModBlocks.DEEPSLATE_ZINC_ORE);
	public static final RegistryObject<Item> ZINC_DUST = REGISTRY.register("zinc_dust", () -> new ZincDustItem());
	public static final RegistryObject<Item> ZINC_BLOCK = block(OrePlusModBlocks.ZINC_BLOCK);
	public static final RegistryObject<Item> METAL_SCRAP_BLOCK = block(OrePlusModBlocks.METAL_SCRAP_BLOCK);
	public static final RegistryObject<Item> AETHERIUM_STAR = REGISTRY.register("aetherium_star", () -> new AetheriumStarItem());
	public static final RegistryObject<Item> AETHERIUM_BLOCK = block(OrePlusModBlocks.AETHERIUM_BLOCK, new Item.Properties().rarity(Rarity.EPIC));
	public static final RegistryObject<Item> AETHERIUM_TOOL = REGISTRY.register("aetherium_tool", () -> new AetheriumToolItem());
	public static final RegistryObject<Item> AETHELGARD_DEBRIS = block(OrePlusModBlocks.AETHELGARD_DEBRIS, new Item.Properties().fireResistant());
	public static final RegistryObject<Item> AETHELGARD_SHARD = REGISTRY.register("aethelgard_shard", () -> new AethelgardShardItem());
	public static final RegistryObject<Item> AETHELGARD_INGOT = REGISTRY.register("aethelgard_ingot", () -> new AethelgardIngotItem());
	public static final RegistryObject<Item> AETHELGARD_BLOCK = block(OrePlusModBlocks.AETHELGARD_BLOCK, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant());
	public static final RegistryObject<Item> AETHELGARD_SWORD = REGISTRY.register("aethelgard_sword", () -> new AethelgardSwordItem());
	public static final RegistryObject<Item> AETHELGARD_PICKAXE = REGISTRY.register("aethelgard_pickaxe", () -> new AethelgardPickaxeItem());
	public static final RegistryObject<Item> AETHELGARD_AXE = REGISTRY.register("aethelgard_axe", () -> new AethelgardAxeItem());
	public static final RegistryObject<Item> AETHELGARD_SHOVEL = REGISTRY.register("aethelgard_shovel", () -> new AethelgardShovelItem());
	public static final RegistryObject<Item> AETHELGARD_HOE = REGISTRY.register("aethelgard_hoe", () -> new AethelgardHoeItem());
	public static final RegistryObject<Item> OBSIDIANITE_DEBRIS = block(OrePlusModBlocks.OBSIDIANITE_DEBRIS, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant());
	public static final RegistryObject<Item> OBSIDIANITE_SHARD = REGISTRY.register("obsidianite_shard", () -> new ObsidianiteShardItem());
	public static final RegistryObject<Item> OBSIDIANITE_INGOT = REGISTRY.register("obsidianite_ingot", () -> new ObsidianiteIngotItem());
	public static final RegistryObject<Item> OBSIDIANITE_BLOCK = block(OrePlusModBlocks.OBSIDIANITE_BLOCK, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant());
	public static final RegistryObject<Item> OBSIDIANITE_SWORD = REGISTRY.register("obsidianite_sword", () -> new ObsidianiteSwordItem());
	public static final RegistryObject<Item> OBSIDIANITE_PICKAXE = REGISTRY.register("obsidianite_pickaxe", () -> new ObsidianitePickaxeItem());
	public static final RegistryObject<Item> OBSIDIANITE_AXE = REGISTRY.register("obsidianite_axe", () -> new ObsidianiteAxeItem());
	public static final RegistryObject<Item> OBSIDIANITE_SHOVEL = REGISTRY.register("obsidianite_shovel", () -> new ObsidianiteShovelItem());
	public static final RegistryObject<Item> OBSIDIANITE_HOE = REGISTRY.register("obsidianite_hoe", () -> new ObsidianiteHoeItem());
	public static final RegistryObject<Item> PYRALITE_DEBRIS = block(OrePlusModBlocks.PYRALITE_DEBRIS, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant());
	public static final RegistryObject<Item> PYRALITE_BLOCK = block(OrePlusModBlocks.PYRALITE_BLOCK, new Item.Properties().rarity(Rarity.UNCOMMON).fireResistant());
	public static final RegistryObject<Item> PYRALITE_SHARD = REGISTRY.register("pyralite_shard", () -> new PyraliteShardItem());
	public static final RegistryObject<Item> PYRALITE_INGOT = REGISTRY.register("pyralite_ingot", () -> new PyraliteIngotItem());
	public static final RegistryObject<Item> PYRALITE_SWORD = REGISTRY.register("pyralite_sword", () -> new PyraliteSwordItem());
	public static final RegistryObject<Item> PYRALITE_PICKAXE = REGISTRY.register("pyralite_pickaxe", () -> new PyralitePickaxeItem());
	public static final RegistryObject<Item> PYRALITE_AXE = REGISTRY.register("pyralite_axe", () -> new PyraliteAxeItem());
	public static final RegistryObject<Item> PYRALITE_SHOVEL = REGISTRY.register("pyralite_shovel", () -> new PyraliteShovelItem());
	public static final RegistryObject<Item> PYRALITE_HOE = REGISTRY.register("pyralite_hoe", () -> new PyraliteHoeItem());
	public static final RegistryObject<Item> RAW_SILVER = REGISTRY.register("raw_silver", () -> new RawSilverItem());
	public static final RegistryObject<Item> RAW_PLATINUM = REGISTRY.register("raw_platinum", () -> new RawPlatinumItem());
	public static final RegistryObject<Item> RAW_TUNGSTEN = REGISTRY.register("raw_tungsten", () -> new RawTungstenItem());
	public static final RegistryObject<Item> RAW_COBALT = REGISTRY.register("raw_cobalt", () -> new RawCobaltItem());
	public static final RegistryObject<Item> RAW_NICKEL = REGISTRY.register("raw_nickel", () -> new RawNickelItem());
	public static final RegistryObject<Item> RAW_PALLADIUM = REGISTRY.register("raw_palladium", () -> new RawPalladiumItem());
	public static final RegistryObject<Item> RAW_NEODYMIUM = REGISTRY.register("raw_neodymium", () -> new RawNeodymiumItem());
	public static final RegistryObject<Item> SULFUR = REGISTRY.register("sulfur", () -> new SulfurItem());
	public static final RegistryObject<Item> SULFUR_BLOCK = block(OrePlusModBlocks.SULFUR_BLOCK);
	public static final RegistryObject<Item> GRAPHITE = REGISTRY.register("graphite", () -> new GraphiteItem());
	public static final RegistryObject<Item> GRAPHITE_BLOCK = block(OrePlusModBlocks.GRAPHITE_BLOCK);
	public static final RegistryObject<Item> BAUXITE = REGISTRY.register("bauxite", () -> new BauxiteItem());
	public static final RegistryObject<Item> BAUXITE_BLOCK = block(OrePlusModBlocks.BAUXITE_BLOCK);
	public static final RegistryObject<Item> CINNABAR = REGISTRY.register("cinnabar", () -> new CinnabarItem());
	public static final RegistryObject<Item> CINNABAR_BLOCK = block(OrePlusModBlocks.CINNABAR_BLOCK);
	public static final RegistryObject<Item> BORAX = REGISTRY.register("borax", () -> new BoraxItem());
	public static final RegistryObject<Item> BORAX_BLOCK = block(OrePlusModBlocks.BORAX_BLOCK);
	public static final RegistryObject<Item> GALENA = REGISTRY.register("galena", () -> new GalenaItem());
	public static final RegistryObject<Item> GALENA_BLOCK = block(OrePlusModBlocks.GALENA_BLOCK);
	public static final RegistryObject<Item> MAGNETITE = REGISTRY.register("magnetite", () -> new MagnetiteItem());
	public static final RegistryObject<Item> MAGNETITE_BLOCK = block(OrePlusModBlocks.MAGNETITE_BLOCK);
	public static final RegistryObject<Item> HEMATITE = REGISTRY.register("hematite", () -> new HematiteItem());
	public static final RegistryObject<Item> HEMATITE_BLOCK = block(OrePlusModBlocks.HEMATITE_BLOCK);
	public static final RegistryObject<Item> MALACHITE = REGISTRY.register("malachite", () -> new MalachiteItem());
	public static final RegistryObject<Item> MALACHITE_BLOCK = block(OrePlusModBlocks.MALACHITE_BLOCK);
	public static final RegistryObject<Item> AZURITE = REGISTRY.register("azurite", () -> new AzuriteItem());
	public static final RegistryObject<Item> AZURITE_BLOCK = block(OrePlusModBlocks.AZURITE_BLOCK);
	public static final RegistryObject<Item> CERIUM = REGISTRY.register("cerium", () -> new CeriumItem());
	public static final RegistryObject<Item> CERIUM_BLOCK = block(OrePlusModBlocks.CERIUM_BLOCK);
	public static final RegistryObject<Item> SILVER_ARMOR_HELMET = REGISTRY.register("silver_armor_helmet", () -> new SilverArmorItem.Helmet());
	public static final RegistryObject<Item> SILVER_ARMOR_CHESTPLATE = REGISTRY.register("silver_armor_chestplate", () -> new SilverArmorItem.Chestplate());
	public static final RegistryObject<Item> SILVER_ARMOR_LEGGINGS = REGISTRY.register("silver_armor_leggings", () -> new SilverArmorItem.Leggings());
	public static final RegistryObject<Item> SILVER_ARMOR_BOOTS = REGISTRY.register("silver_armor_boots", () -> new SilverArmorItem.Boots());
	public static final RegistryObject<Item> NICKEL_ARMOR_HELMET = REGISTRY.register("nickel_armor_helmet", () -> new NickelArmorItem.Helmet());
	public static final RegistryObject<Item> NICKEL_ARMOR_CHESTPLATE = REGISTRY.register("nickel_armor_chestplate", () -> new NickelArmorItem.Chestplate());
	public static final RegistryObject<Item> NICKEL_ARMOR_LEGGINGS = REGISTRY.register("nickel_armor_leggings", () -> new NickelArmorItem.Leggings());
	public static final RegistryObject<Item> NICKEL_ARMOR_BOOTS = REGISTRY.register("nickel_armor_boots", () -> new NickelArmorItem.Boots());
	public static final RegistryObject<Item> GADOLINIUM_ARMOR_HELMET = REGISTRY.register("gadolinium_armor_helmet", () -> new GadoliniumArmorItem.Helmet());
	public static final RegistryObject<Item> GADOLINIUM_ARMOR_CHESTPLATE = REGISTRY.register("gadolinium_armor_chestplate", () -> new GadoliniumArmorItem.Chestplate());
	public static final RegistryObject<Item> GADOLINIUM_ARMOR_LEGGINGS = REGISTRY.register("gadolinium_armor_leggings", () -> new GadoliniumArmorItem.Leggings());
	public static final RegistryObject<Item> GADOLINIUM_ARMOR_BOOTS = REGISTRY.register("gadolinium_armor_boots", () -> new GadoliniumArmorItem.Boots());
	public static final RegistryObject<Item> CHROMIUM_SWORD = REGISTRY.register("chromium_sword", () -> new ChromiumSwordItem());
	public static final RegistryObject<Item> CHROMIUM_PICKAXE = REGISTRY.register("chromium_pickaxe", () -> new ChromiumPickaxeItem());
	public static final RegistryObject<Item> CHROMIUM_AXE = REGISTRY.register("chromium_axe", () -> new ChromiumAxeItem());
	public static final RegistryObject<Item> CHROMIUM_SHOVEL = REGISTRY.register("chromium_shovel", () -> new ChromiumShovelItem());
	public static final RegistryObject<Item> CHROMIUM_HOE = REGISTRY.register("chromium_hoe", () -> new ChromiumHoeItem());
	public static final RegistryObject<Item> BRONZE_ARMOR_HELMET = REGISTRY.register("bronze_armor_helmet", () -> new BronzeArmorItem.Helmet());
	public static final RegistryObject<Item> BRONZE_ARMOR_CHESTPLATE = REGISTRY.register("bronze_armor_chestplate", () -> new BronzeArmorItem.Chestplate());
	public static final RegistryObject<Item> BRONZE_ARMOR_LEGGINGS = REGISTRY.register("bronze_armor_leggings", () -> new BronzeArmorItem.Leggings());
	public static final RegistryObject<Item> BRONZE_ARMOR_BOOTS = REGISTRY.register("bronze_armor_boots", () -> new BronzeArmorItem.Boots());
	public static final RegistryObject<Item> BRONZE_SWORD = REGISTRY.register("bronze_sword", () -> new BronzeSwordItem());
	public static final RegistryObject<Item> BRONZE_PICKAXE = REGISTRY.register("bronze_pickaxe", () -> new BronzePickaxeItem());
	public static final RegistryObject<Item> BRONZE_AXE = REGISTRY.register("bronze_axe", () -> new BronzeAxeItem());
	public static final RegistryObject<Item> BRONZE_SHOVEL = REGISTRY.register("bronze_shovel", () -> new BronzeShovelItem());
	public static final RegistryObject<Item> BRONZE_HOE = REGISTRY.register("bronze_hoe", () -> new BronzeHoeItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return block(block, new Item.Properties());
	}

	private static RegistryObject<Item> block(RegistryObject<Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}
}